### ISSUE TITLE
Does the Fiber has localization function?How to switch multi language?🚀 

### ISSUE THREAD

**Issue by limncoin** [gofiber/fiber#1001]
How to switch multi language?
thanks!

**Comment by codemicro** [comment]
Hi @limncoin!

**Unfortunately, Fiber has no built in localisation options.** This would be something you'd have to implement yourself, since Fiber is purely a web framework to build your app on top of. 

You might be able to achieve this with a custom middleware that detects what language should be selected for a specific request and stores this value in [`Locals`](https://docs.gofiber.io/api/ctx#locals), which you can then use in your handlers to modify the response that is returned.
