### ISSUE TITLE
🐛 UnescapePath not working

### ISSUE THREAD

**Issue by mhf-ir** [gofiber/fiber#1102]
**Fiber version**
```
github.com/gofiber/fiber/v2 v2.3.2
```
**Issue description**
Params not unescape

**Code snippet**

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New(fiber.Config{
		DisableStartupMessage: true,
		Prefork:               true,

		UnescapePath: true,
		// UnescapePath:  false,

		CaseSensitive: true,
		StrictRouting: true,
		BodyLimit:     1 * 128,
	})

	app.Get("/who-am-i/:name", func(c *fiber.Ctx) error {
		// with UnescapePath: true FAILED
		name := c.Params("name")

		// with UnescapePath: false SUCCESS
		// name, err := url.PathUnescape(c.Params("name"))
		// fmt.Println(err)
		// fmt.Println(name)

		fmt.Println(name)
		return c.SendString("Hello, " + name + "\n")
	})

	app.Listen(":3000")
}
```

```
sweb@sweb-laptop:~$ curl 'http://localhost:3000/who-am-i/%D9%85%D8%AD%D9%85%D8%AF'
Hello, %D9%85%D
```

Manual unescape will success get unicode param

```
sweb@sweb-laptop:~$ curl 'http://localhost:3000/who-am-i/%D9%85%D8%AD%D9%85%D8%AF'
Hello, محمد
```

**Comment by ReneWerner87** [comment]
thanks for your report, this switch is currently only there so that the routing can handle the non-encoded url parameters
https://github.com/gofiber/fiber/blob/master/app.go#L140-L144
![image](https://user-images.githubusercontent.com/7063188/103642834-05516680-4f54-11eb-838d-71ce1899d1da.png)

maybe the name is badly chosen, i'll ask the other maintainers how to proceed, if we change the name or get the paramters decoded or proceed differently

**Comment by ReneWerner87** [comment]
@mhf-ir we are working on the fix -> PR https://github.com/gofiber/fiber/pull/1104/files
