### ISSUE TITLE
🤗 I don't understand how to use middleware csrf

### ISSUE THREAD

**Issue by GarryGaller** [gofiber/fiber#1237]
If I do it like this
```
csrfConfig := csrf.Config{ContextKey:"csrf", KeyLookup: "cookie:csrf"}
csrfGroup := app.Group("/", csrf.New(csrfConfig))
csrfGroup.Get("/login", t.LoginForm)
csrfGroup.Post("/auth", t.LoginAuthorize)   
    
```
then I get forbidden for all requests.

If like this
```
csrfConfig := csrf.Config{ContextKey:"csrf", KeyLookup: "cookie:csrf"}
app.Get("/login", csrf.New(csrfConfig), t.LoginForm)
app.Post("/auth", t.LoginAuthorize)
```

then I can safely make an authorization request from the script and I am not hindered by the lack of a token

**Comment by GarryGaller** [comment]
OK. I did this: the csrf token is written to the hidden field of the login form.
And the authorization handler checks:

```
type Auth struct {
        Login    string
        Password string
        Csrf     string
    }

    auth := Auth{}
    //-----------------------------------------
    if err := c.BodyParser(&auth); err != nil {
        t.Log.Errorf("[AUTH:BODY]: %#v\n", err)
        
        data["Error"] = true
        data["Message"] = err.Error()
        
        if e, ok := err.(*fiber.Error); ok {
            data["Code"] = e.Code
            data["Message"] = err.Error()
            return c.Status(e.Code).Render("50x", data, "50x")
        }
        
        return c.Render("login_form", data, "login_form")
    }
    csrfFromCookies := c.Cookies("csrf_")
    csrfFromForm := auth.Csrf
    t.Log.Tracef("[CSRF:COOKIE]: %#v\n", csrfFromCookies)
    t.Log.Tracef("[CSRF:FORM]: %#v\n", csrfFromForm)
    
    if csrfFromCookies == "" || csrfFromForm =="" || csrfFromCookies != csrfFromForm {
        data["Code"] = fiber.StatusForbidden
        data["Message"] = http.StatusText(fiber.StatusForbidden)
        return c.Status(fiber.StatusForbidden).Render("50x", data, "50x")
    }
```

But what protection does this provide if the token can be easily parsed from html code?

**Comment by ReneWerner87** [comment]
Hi, everything can be read from the browser if it has become a security risk due to other vulnerabilities

To provide protection against csrf, another information should be sent for confirmation by a hidden field

This method only helps with this type of security vulnerability, if the browser has already been attacked by xss vulnerabilities, this of course does not help anymore.

Here a really good article about csrf
https://owasp.org/www-community/attacks/csrf
With the description and prevention solutions


If you have no further questions, please feel free to close the issue.

**Comment by GarryGaller** [comment]
Can you tell me if I used your middleware correctly in my example?
You just don't have a single real life example for a real application in your documentation. And so questions arise.

**Comment by ReneWerner87** [comment]
Okay we will provide an example in the recipe repository, thanks for the hint

Unfortunately i didn't write the middleware and i never used it myself, 

after the code research i would say, you don't have to do anything, because the cookie is set in the HEAD, GET, OPTIONS, TRACE request and if one of the other request methods is used, it will be evaluated in the next request, depending on what you used as KeyLookup, i.e. the token can be set in form, header, query parameters, route parameter or cookie

To write it, you can go to the locals of the context, for this also the context key was set in the config

But that leads me to the question why it didn't work with your first example

When i prepare the example i will experiment a little bit

**Comment by ReneWerner87** [comment]
@GarryGaller 
have added an example for you

could also not see any errors in the use of the csrf middleware
https://github.com/gofiber/recipes/pull/111
