### ISSUE TITLE
🤗 How to implement i18n?

### ISSUE THREAD

**Issue by tomaswarynyca** [gofiber/fiber#1240]
Hi, would you be so kind to provide a template with i18n to answer a request identifying the language of the client and also be able to use in .html views?

**Comment by hi019** [comment]
What about https://github.com/nicksnyder/go-i18n ? It seems to be web framework agnostic and has a built in cli as well as TOML parsing

**Comment by tomaswarynyca** [comment]
I have been doing some research and the one that convinces me the most is this one that works in `.ini`
https://github.com/unknwon/i18n

As we talked on discord it would be nice to have native support.
It would have to be implemented to look for all the `.ini` in a folder and add them as supported language, in the case of the one that passes it is done in the following way `i18n.SetMessage(lang, file)`


```
app.Get("/", func(c *fiber.Ctx) error {
	_ = i18n.SetMessage("en-US", "locales/en-US.ini")
	i18n.SetDefaultLang("en-US")
	return c.SendString(i18n.Tr("", "home"))
})
```
Here I implemented it for a response, it returns the `Home` value that is in `en-US.ini`, the issue is how to do it to be able to request the translations from any part of the app.

**Comment by ReneWerner87** [comment]
You are welcome to provide such a middleware, we also link to external solutions that work with fiber

Currently there is no native implementation planned, we want to keep fiber as lean and general as possible, only the basic middlewares that everyone uses made it into the core, everything else will be added via extra repository in form of middlewares

Since i18n does not play a role in every service it should find a place outside.

**Comment by koddr** [comment]
Hey, @tomaswarynyca

I add a new Fiber's recipe with [nicksnyder/go-i18n](https://github.com/nicksnyder/go-i18n) package [here](https://github.com/gofiber/recipes/tree/master/i18n).

Hope, this helps 👍
