### ISSUE TITLE
Remove Error Handling

### ISSUE THREAD

**Issue by atkisai** [gofiber/fiber#1242]
Tell me how can I remove the interface error in function becose Gorm API Error does not work.

db.Model(&p1).Association("Friends").Find(&p2).Error <= This NOT work
db.Model(&p1).Association("Friends").Error <= This work

**Comment by ReneWerner87** [comment]
Hi, gorm is not a product that comes from the fiber community, you should ask your question there in the github project, at the same time I would recommend you to formulate it a bit more concrete and with more example code, because I just do not understand the core of the problem, but as I also mentioned, we are not experts in this.

I close this issue here, because there is no connection to the project

but feel free to report other questions or bugs that are related to fiber and where you are currently stuck despite your own research and testing.

**Comment by hi019** [comment]
This is an issue tracker for Fiber bugs, this sound likes it is an issue with GORM. You would be better off asking in [GORM issues](https://github.com/go-gorm/gorm/issues)
