### ISSUE TITLE
🐛  middleware compress error

### ISSUE THREAD

**Issue by Refuel-ZL** [gofiber/fiber#1244]
**Fiber version**
v2.6.0
**Issue description**
Level: compress.LevelBestSpeed
panic: runtime error: index out of range [512] with length 512

compress.LevelBestCompression、compress.LevelDefault  No problem

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

******
//go:embed "static/*"
var f embed.FS
******

func main() {
  app := fiber.New()

  // Steps to reproduce
        app.Use(compress.New(compress.Config{
		Next: func(c *fiber.Ctx) bool {
			return !strings.HasPrefix(c.Path(), strings.TrimRight(config.StatusDir, "/"))
		},
		Level: compress.LevelBestSpeed,
	}))
  log.Fatal(app.Listen(":3000"))
}
```
![image](https://user-images.githubusercontent.com/22957560/112708403-d3192a80-8eec-11eb-9dc6-5edbb6e03f60.png)

**Comment by ReneWerner87** [comment]
Thanks for the report

Unfortunately the setup to reproduce is broken, because the statusDir as important information as well as the config is missing

Also the route and if necessary examples of the file structure are missing

Furthermore i wonder why embed filesystem is mined, but nowhere used in the example

As i don't have the complete example, but see the section with the embed filesystem, i could assume that it has something to do with the new go1.16 feature, which is not integrated or fully supported in fasthttp at this time.

**Comment by ReneWerner87** [comment]
@Refuel-ZL

**Comment by ReneWerner87** [comment]
if the problem persists, then reopen the issue, at the current time we can not do without an example to reproduce
