### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by 5paceToast** [gofiber/fiber#132]
**Is your feature request related to a problem?**
By default in most jurisdictions, any creative endeavor is copyrighted ("all rights reserved").
This makes using the project difficult, legally speaking, especially in environments where that's a concern (even if no one has the intention of starting a legal action).

**Describe the solution you'd like**
Add a LICENSE file.
Optionally, also have some form of CLA or similar (at least for already-contributed-contributors).
I personally prefer the Unlicense (available under choose-a-license), but any license would be fine.

**Describe alternatives you've considered**
Alternatively, you could grant individual licenses to anyone that asks, but that places undue burden on the project maintainers.
Regarding license choices, other popular alternatives include MIT and GPL3.

**Additional context**

**Comment by MarvinJWendt** [comment]
Hi @5paceToast, the license file is located here: https://github.com/gofiber/fiber/blob/master/.github/LICENSE (`.github/LICENSE`)

@Fenny I think this should be moved to the root of the project, so that GitHub can display it here:
![image](https://user-images.githubusercontent.com/31022056/74356318-73ca8a80-4dbe-11ea-96b4-ed319d26c362.png)

**Comment by 5paceToast** [comment]
> I think this should be moved to the root of the project

definitely, especially since the license doesn't *just* apply to github users, and isn't really meaningless metadata (forks will need to include and modify it as well)
