### ISSUE TITLE
🤗"Static" method file handle takes too long 

### ISSUE THREAD

**Issue by liaohongxing** [gofiber/fiber#1338]
**Fiber version**
v2.10.0
**Issue description**
"Static" method file handle takes too long , Cannot be deleted immediately 
**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Static("/public", "./public")

	app.Listen(":3005")
}
```

![D](https://user-images.githubusercontent.com/35255844/118792826-9bb27300-b8ca-11eb-97bb-6b417521e5b6.gif)

**Comment by ReneWerner87** [comment]
fiber uses the feature of fasthttp(https://github.com/valyala/fasthttp/blob/master/fs.go) under the hood and there the workflow has been optimized so that the content delivered as fast as possible, with very many tricks on a very deep level

don't think we could solve that here, besides the browser cache for the display also plays a role

have you ever tried to delete the file using golang or other automations ?

**Comment by liaohongxing** [comment]
@ReneWerner87 
This is just a simple example. My problem is that once the access behavior occurs, the file cannot be deleted, which is very unfavorable for me to write the UI interface.

**Comment by Fenny** [comment]
@liaohongxing did you try to reduce the file handler [cache duration](https://docs.gofiber.io/api/app#static)?
```go
app.Static("/", "./public", fiber.Static{
  CacheDuration: 10 * time.Second,
})
```

**Comment by liaohongxing** [comment]
@Fenny 
This option works and temporarily solves the problem

**Comment by liaohongxing** [comment]
"os.remove" is already working

**Comment by ReneWerner87** [comment]
ok perfect
