### ISSUE TITLE
🐛 pprof middleware redirect index page to wrong url

### ISSUE THREAD

**Issue by kurefm** [gofiber/fiber#1360]
**Fiber version**

v2.11.0

**Issue description**

The pprof middleware **should** redirect `/debug/pprof` to `/debug/pprof/`, but not redirect `/debug/pprof/` to `/debug/pprof`.

Because of pprof index page use relative herf path, `/debug/pprof` make sub page (e.g `/debug/pprof/allocs`) herf link become `/debug/allocs`

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/1330

**Comment by ReneWerner87** [comment]
@bestgopher you have customized this exact place in the pull request, can you give feedback on this issue

**Comment by bestgopher** [comment]
@kurefm Could you fix the bug?

**Comment by bestgopher** [comment]
@ReneWerner87 Sorry for this bug caused by me. I think pprof as a middleware is not a good choice, it should be registered in the router. As a middleware, everyone can access this path, and it is difficult for us to authenticate it.

**Comment by ReneWerner87** [comment]
what do you mean that it should be registered in the router and not as middleware ? via middleware a handler is registered and the same possibility exists also only in the router

besides it is better kept as a separate middleware, because it can then be used by anyone who wants or left out.

what do you mean by the last sentence, you can put another middleware in front of the middleware and do any kind of check if a request is allowed to access here or not, that's the advantage of the middlewares and the chaining of them

but more importantly who makes the fix ? @bestgopher or @kurefm ?

**Comment by bestgopher** [comment]
> what do you mean that it should be registered in the router and not as middleware ? via middleware a handler is registered and the same possibility exists also only in the router
> 
> besides it is better kept as a separate middleware, because it can then be used by anyone who wants or left out.
> 
> what do you mean by the last sentence, you can put another middleware in front of the middleware and do any kind of check if a request is allowed to access here or not, that's the advantage of the middlewares and the chaining of them
> 
> but more importantly who makes the fix ? @bestgopher or @kurefm ?

How to achieve this：

```
        app := fiber.New()

	{
		// pprof
		p := app.Group(
			"/debug/pprof",
			basicauth.New(basicauth.Config{Users: map[string]string{"pprof": "pprof"}},
			),
		)

		p.Get("/", func(ctx *fiber.Ctx) error {
			fasthttpadaptor.NewFastHTTPHandlerFunc(pprof.Index)(ctx.Context())
			return nil
		})

		p.Get("/cmdline", func(ctx *fiber.Ctx) error {
			fasthttpadaptor.NewFastHTTPHandlerFunc(pprof.Cmdline)(ctx.Context())
			return nil
		})
	}
	app.Listen(":3000")
```
