### ISSUE TITLE
🐛 middleware/session/session delete is not working 

### ISSUE THREAD

**Issue by wushimang886** [gofiber/fiber#1365]
the session mod can not be delete
My operation is as follows

session.set("key1", "value1")
session.save()
session.Delete("key1")
session.save()
when Get session again the key “key1” is still exists
in file fiber/middleware/session/session.go
line 138
if s.data.Len() <= 0 {
return nil
}

when Delete("key1") the data.Len() is 0
so the date is not save

**Comment by ReneWerner87** [comment]
@wushimang886 sorry only english is allowed, please adjust the language otherwise we can not help you

**Comment by wushimang886** [comment]
the session mod can not be delete
My operation is as follows
1. session.set("key1", "value1")
2. session.save()
3. session.Delete("key1")
4. session.save()

when Get session again the key “key1” is  still exists
in file fiber/middleware/session/session.go 
line 138
if s.data.Len() <= 0 {
return nil
}

when Delete("key1") the data.Len() is 0
so the date is not save

**Comment by hi019** [comment]
This happens when there is only one key in the session and it's deleted. When `session.Delete(k)` is called, the key is only removed from the internal map and not yet from the database. So that if statement is true and no data will be saved as you said.

We can remove the if statement, but I'm thinking if that will be a breaking change. Alternatively we could have `session.Delete` save the data itself.

https://github.com/gofiber/fiber/blob/master/middleware/session/session.go#L138-L141

**Comment by ReneWerner87** [comment]
I look in later
