### ISSUE TITLE
Performance issue with simple App.Use of CSRF middleware 

### ISSUE THREAD

**Issue by gitMitos** [gofiber/fiber#1371]
By simply adding 

`app.Use(csrf.New(csrf.Config{
	 	KeyLookup:  "form:form_csrf",
		CookieName: "csrf_",
	 	ContextKey: "csrf",
	 }))`

i have significant drop of request/second on helloworld like app

With it i have 65k-75k req/sec on endpoint

`app.Get("/hi", func(c *fiber.Ctx) error {
		return c.SendString("hi")
	})`

if i delete it - i will be getting about 179k-181k req/sec

Is it price of having csrf middleware in general or this specific implementation is not a best one? Does anyone else have same issue?

**Comment by ReneWerner87** [comment]
> Is it price of having csrf middleware in general or this specific implementation is not a best one? Does anyone else have same issue?

yes right, security usually comes at the cost of performance, because checks have to be made and data has to be stored

probably we can optimize the middleware even further, for this you or anyone else like to deposit a pull request

**Comment by ReneWerner87** [comment]
here you could use the sync pool
https://github.com/gofiber/fiber/blob/master/middleware/csrf/csrf.go#L68

think storing in storage is also a big performance eater

**Comment by GibranHL0** [comment]
Hey 👋 , It seems like an interesting issue.
Can I give it a shot?

**Comment by hi019** [comment]
Sure @GibranHL0 , I'll assign you

**Comment by GibranHL0** [comment]
Great, I'll make the proposal as soon as possible.

**Comment by GibranHL0** [comment]
Hey, I've been doing some stress tests using the same [tool](https://github.com/smallnest/go-web-framework-benchmark) as in the README file.

I created a hello world like app as in the issue statement.
```go
app.Get("/hello", func(c *fiber.Ctx) error { return c.SendString("hi") })
```

The scenarios I used were

1. Fiber without CSRF enabled
2. CSRF enabled
```go
app.Use(csrf.New(csrf.Config{ KeyLookup: "form:form_csrf", CookieName: "csrf_", ContextKey: "csrf", }))
```
3. CSFR with sync.pool (I had to assign the values to the Cookie, otherwise it will fill them with the zero values)
```go
var cPool = sync.Pool{
	New: func() interface{} { return new(fiber.Cookie) },
}

cookie := cPool.Get().(*fiber.Cookie)

defer cPool.Put(cookie)

cookie.Name = cfg.CookieName
cookie.Domain = cfg.CookieDomain
cookie.Path = cfg.CookiePath
cookie.Expires = time.Now().Add(cfg.Expiration)
cookie.Secure = cfg.CookieSecure
cookie.HTTPOnly = cfg.CookieHTTPOnly
cookie.SameSite = cfg.CookieSameSite
```
The results I got are based on req/sec:
Clients | Fiber/2.13 (req/sec)| Fiber/2.13 CSRF (req/sec)| SyncPool (req/sec)
-- | -- | -- | --
100 | 222610.82 | 114483.22 | 114855.74
1000 | 244646.77 | 115430.55 | 116079.23
5000 | 243173.64 | 114837.73 | 114950.12

And the improvement % of using one implementation against the other:
Fiber/2.13 CSRF (req/sec) | SyncPool (req/sec) | Improvement %
-- | -- | --
114483.22 | 114855.74 | 0.3243372948
115430.55 | 116079.23 | 0.5588252093
114837.73 | 114950.12 | 0.09777284269

Then, I believe the current implementation is great enough. Also, I've researched other implementations like Gorilla, and they took the same approach.

What do you think @hi019, should we consider applying the sync pool, or did I miss something?

**Comment by gitMitos** [comment]
it is still huge (more then twice) drop in performance :(  
I wonder if jwt (or plaint eas encypted cookie with json) with extra data (random number per session) for csrf (check if hash(random_number + some_site_key) == to token in html form) could be better solution for auth and for csrf

**Comment by hi019** [comment]
@GibranHL0 thanks for the charts. From your response, I'm not sure if its worth the complexity. We haven't profiled it yet, but I assume most of the performance loss is from using the storage interfaces as Rene said. 

It seems like Gorilla's implementation doesn't use a database, we should check if the Fiber middleware can do a similar thing https://github.com/gorilla/csrf#design-notes

**Comment by ReneWerner87** [comment]
> It seems like Gorilla's implementation doesn't use a database, we should check if the Fiber middleware can do a similar thing

good point

**Comment by silviucm** [comment]
@ReneWerner87  @hi019  Please note that the line 
[https://github.com/gofiber/fiber/blob/master/internal/memory/memory.go#L26](https://github.com/gofiber/fiber/blob/master/internal/memory/memory.go#L26)

`go store.gc(10 * time.Millisecond)`

Appears to be brutally skew against high performance. At least in my profiling the culprit seems to be the gc fellow method being invoked way too often for its own good. Maybe a compromise between CPU and memory usage should be made and 100 or 1000 ms should be considered ? (just a suggestion)

**Comment by ad3n** [comment]
Sorry, any update here?
