### ISSUE TITLE
🐛 QueryParser returns no error when required field is empty

### ISSUE THREAD

**Issue by tuhao1020** [gofiber/fiber#1414]
```go
type QueryParams struct {
	Name string `query:"name,required"`
	Addr string `query:"addr,required"`
}

func ParseHandler(ctx *fiber.Ctx) error {
	param := new(QueryParams)
	err := ctx.QueryParser(param)
	if err != nil {
		ctx.Write([]byte(err.Error()))
	} else {
		err = ctx.JSON(param)
	}
	return err
}
```

http://localhost:8080/test?nameaaa=hello&addrbbb=world

```json
{
  "Name": "",
  "Addr": ""
}
```

http://localhost:8080/test?n=hello&addrbbb=world

```
name is empty
```

The above two cases are expected to return the following contents：

```
name is empty (and 1 other error)
```

**Comment by tuhao1020** [comment]
L160: `strings.HasPrefix(key, path)` should be `key == path` ?

https://github.com/gofiber/fiber/blob/28ba42a6fd89b0a94de241931ba2ce1503d78fef/internal/schema/decoder.go#L151-L167

**Comment by ReneWerner87** [comment]
think it was solved with hasPrefix, because in deeper structures, they wanted to check the previous parts


https://github.com/gorilla/schema/blob/master/decoder.go#L160
https://github.com/gorilla/schema/pull/126
https://github.com/gorilla/schema/commit/61751c9687439bf8cd824ad7eec0d21db1a1b804

here is also an issue about it
-> https://github.com/gorilla/schema/issues/176

maybe you can support it and give some information, as soon as it is adjusted in the library, i can try to take it over

**Comment by tuhao1020** [comment]
@ReneWerner87 do you mean nested struct like this?

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/123915923-4cf40080-d981-11eb-94f9-5350f33f6ad4.png)

**Comment by tuhao1020** [comment]
@ReneWerner87 
```go
type R2 struct {
	A struct {
		B int `query:"b"`
	} `query:"a,required"`
}
```

I think if A has no required fields , it does't need to keep a `required` option.

**Comment by ReneWerner87** [comment]
i know, only the test was filed with the adjustments you noted
and I think that's where the check with hasPrefix comes from

he wanted to check if a is prepended in the string

**Comment by tuhao1020** [comment]
@ReneWerner87  I created a PR to gorilla/schema, but no one seems to handle it,  can I make the a PR directly to fiber?

**Comment by ReneWerner87** [comment]
you can also provide one here
