### ISSUE TITLE
🐛 When adding any GET handler, the App.handleCount is being incremented twice.

### ISSUE THREAD

**Issue by monticello** [gofiber/fiber#1435]
**Fiber version**
2.14.0
**Issue description**
When adding any GET handler, the App.handleCount is being incremented twice.

**Cause**
The double incrementation is because only for the GET registration, the HEADER is also registered.

Maybe it is correct to register the header (is it?), but it is weird to duplicate the handleCount because of it.

**Code snippet when adding the GET**
https://github.com/gofiber/fiber/blob/master/app.go#L525
```go
func (app *App) Get(path string, handlers ...Handler) Router {
	return app.Add(MethodHead, path, handlers...).Add(MethodGet, path, handlers...)
}
```
**Code snippet when incrementing the counter **
https://github.com/gofiber/fiber/blob/master/router.go#L266
```go
atomic.AddUint32(&app.handlerCount, uint32(len(handlers)))
```

**Comment by ReneWerner87** [comment]
the observation is correct and also so expected

if someone registers a GET handler, then we also register the HEAD
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

the handler count must count up twice, because this handler is duplicated and available twice for different request methods

You should notice the same thing with ALL, because there is also a handler created for each request method.
