### ISSUE TITLE
Is there any possibility for get path template in handler?🤗 

### ISSUE THREAD

**Issue by blessedvictim** [gofiber/fiber#1459]
**Question description**

For example, in `gorilla mux` there is 
```go
var req *http.Request = ...
route := mux.CurrentRoute(req)
route.GetPathTemplate() // return will return something like "/user/{id}"
```

I can find similar thing in fiber, but it seems not working. 

```go
c.Route().Path 
```
It always return "/" inside middleware. May be a bug ?

It may be useful for implementing Elastic APM middleware for expose only url templates to APM. 

There is possibility for get path template ?

i use github.com/gofiber/fiber/v2 v2.15.0

**Comment by blessedvictim** [comment]
Seems like problem here [source code](https://github.com/gofiber/fiber/blob/1e0d4d3b1c67c6a0a4df357f8653583be5f63b42/router.go#L81)
is it exptected behaviour ?

**Comment by ReneWerner87** [comment]
it is not a bug, it is an expected behavior

this property reflects the current route of the handler and in your case you probably didn't specify a route in the middleware, so the starting slash is reflected

**Comment by blessedvictim** [comment]
As i research, workaround for this is look on `c.Router()` after call `c.Next()`. 
Is there any caveeats ? @ReneWerner87

**Comment by ReneWerner87** [comment]
no should be okay

**Comment by blessedvictim** [comment]
Thx, close issue

**Comment by lucasoares** [comment]
Any change to reopen this issue? @ReneWerner87 

In my case, I have a middleware that needs to get the request templated handler.

My middleware will filter specific handlers and call `c.Next()` only if it matches specific conditions using the route Method and the templated handler, otherwise it will return an internal error. It's a security middleware.

Any workaround on this? I can't call `c.Next()` to update the route path since it should only be called if matches a specific condition.

Thanks.
