### ISSUE TITLE
when I use session middleware,it always return same sessionId every time.

### ISSUE THREAD

**Issue by goldwind-ting** [gofiber/fiber#1486]
When I run the following code and request http://localhost:5001/login?name=ban or http://localhost:5001/login?name=wang, the sess.ID() is same in every request.
```go

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/redis"
)

func main() {
	app := fiber.New()
	storage := redis.New(redis.Config{
		Host:     "127.0.0.1",
		Port:     6379,
		Username: "",
		Password: "",
		Database: 0,
		Reset:    false,
	})
	store := session.New(session.Config{
		Storage: storage,
	})
	app.Get("/login", func(c *fiber.Ctx) error {
		// Get session from storage
		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}
		oriName := sess.Get("name")
		name := c.Query("name")
		if oriName == nil {
			sess.Set("name", name)
			if err := sess.Save(); err != nil {
				panic(err)
			}
		}
		return c.SendString(fmt.Sprintf("Welcome %v", name))

	})
	app.Listen(":5001")
}

}
```

**Comment by ReneWerner87** [comment]
Why should the session id not be the same ? that's what a session is for, to persist it over multiple requests and share data.

By the way, you shouldn't use GET to match data, GET requests should be cacheable.

**Comment by goldwind-ting** [comment]
I know that session id is stored in the cookie and reused, but if different users login, they still use same session and session id? and how to generate different session in this case? I am not clear about that.

**Comment by ReneWerner87** [comment]
Ok, oh it's about different use

i.e. you test with 2 different browsers or devices

https://github.com/gofiber/fiber/blob/master/middleware/session/store.go#L54-L56

actually what you say here is not possible, because if there is no id in the cookie, a new id is generated using the keyGen function, which can be specified by the user but does not have to be.

if you use the standard keyGen, a unique id will be generated which should not be assigned again, here I am 100% sure

https://github.com/gofiber/fiber/blob/master/middleware/session/config.go#L74

if you are testing in the same browser, you will of course need to add a function that ends the session and uses the session destroy feature.
https://github.com/gofiber/fiber/blob/master/middleware/session/session.go#L94

**Comment by goldwind-ting** [comment]
Ok, I am clear, I tested the login api with same browser but different user info, and get same session id. I just now tested by `curl` command and browser, it worked, and I could get different session id. Thank you!
