### ISSUE TITLE
🐛Why setup session config with Cookie secure and HttpOnly=true then can not get cookie value in context? 

### ISSUE THREAD

**Issue by phuongdpham** [gofiber/fiber#1491]
**Fiber version**
v2.17.0

**Issue description**
When I set up session store config with CookieSecure=true and HttpOnly=true, then I can't get session from context, it create new id because of not found cookie session_id value. (id := c.Cookies(s.sessionName)). For Key lookup default in Cookie.

**Code snippet**
store.go line 92...

```go
// getSessionID will return the session id from:
// 1. cookie
// 2. http headers
// 3. query string
func (s *Store) getSessionID(c *fiber.Ctx) string {
	id := c.Cookies(s.sessionName)  // return nil while I pass session_id in cookies
	if len(id) > 0 {
		return id
	}

	if s.source == SourceHeader {
		id = string(c.Request().Header.Peek(s.sessionName))
		if len(id) > 0 {
			return id
		}
	}

	if s.source == SourceURLQuery {
		id = c.Query(s.sessionName)
		if len(id) > 0 {
			return id
		}
	}

	return ""
}
```
Please figure out how to retrieve cookie value if it's not a bug issue. Thanks.

**Comment by ReneWerner87** [comment]
can not understand this unfortunately, here is my example code
```go
package main

import (
    "fmt"
    "log"
    "time"

    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/fiber/v2/middleware/session"
)

func main() {
    app := fiber.New()
    store := session.New(session.Config{
        CookieSecure: true,
        CookieHTTPOnly: true,
    })

    app.Get("/sessionId", func(ctx *fiber.Ctx) error {
        sess, err := store.Get(ctx)
        defer sess.Save()
        if err != nil {
            return err
        }

        fmt.Println(time.Now().Format("15:04:05.000000"), sess.ID())
        return ctx.SendString(sess.ID())
    })


    log.Fatalln(app.Listen(":3000"))
}
```

Output:
![image](https://user-images.githubusercontent.com/7063188/129680190-1973c29f-ee37-4ad2-a3e3-baaecc3052b4.png)

please also check if you are running the sess.Save(), otherwise it will create a new session for every request, because there is none in the storage.

**Comment by phuongdpham** [comment]
Hi ReneWerner87,

Thank you for your reply. When I run you sample code, this is my response

![image](https://user-images.githubusercontent.com/12036726/129826424-9b6f215b-559d-40e1-9bce-26116486331d.png)
![image](https://user-images.githubusercontent.com/12036726/129826578-106377cc-51b4-4ab2-a040-8d70e49c4186.png)

I call from postman or curl from terminal sessionId also different. That's so stranger

**Comment by ReneWerner87** [comment]
this is expected behavior and not a bit strange

the session concept only works if the client requesting the server also sends the session id sent in the response in the request the next time so that the server can use it to retrieve the data from the persistence layer and assign it to the client

if you use curl or postman, you have to send this id, which is set by default in the cookie in the response, in the next request.

in the browser this works automatically, because the cookies are taken from the response in the browser and are automatically sent with the next request (such concepts where the client has to remember things, like with the etag header etc.)

curl and postman are stateless and don't remember anything after the request by default

**Comment by phuongdpham** [comment]
Ohh, I see the problem. The postman won't auto set cookie in request if that cookie is secure and http only. Thank you for your explain.
