### ISSUE TITLE
🚀 support message queue

### ISSUE THREAD

**Issue by 1534854467** [gofiber/fiber#1545]
hope to support requests that from rest api and message queue(like. nsq, nats, kafka ...)

Or have any other ways to achieve ？

**Comment by ReneWerner87** [comment]
you can use message queues by using clients from other libraries

but I don't see a packet for fiber here, what benefit should that have ?

just use the connectors that are available for golang

**Comment by 1534854467** [comment]
I try to use fiber to develop a project, and it contains many microservice applications.
some requests almost need call many other microservice at the same time and response merged result；

l learn about event-driven(https://medium.com/trendyol-tech/event-driven-microservice-architecture-91f80ceaa21e) and try it, but I don't know how to accept a request from the message queue and how to response data to message queue by fiber;

how to trigger an api route ?

how to support both restful and message queue in same api route?

like go-kit transport: https://github.com/go-kit/kit/tree/master/transport

and. I am learning source code about fiber and fasthttp ， someone have any suggest？

**Comment by ReneWerner87** [comment]
please check 
https://github.com/gofiber/recipes/tree/master/rabbitmq

probably you misunderstand the event driven stuff a little bit, there you don't talk about message queue in requests, but you create a consumer or worker for the queue, you can see that in the example project, in the folder worker

and by response data you probably mean placing a message on that queue based on a user request, which in the world of message queues is publishing the message to an exchange

you can see in the example project in the main.go of the root folder

to learn more about fiber see the examples in the recipe project (https://github.com/gofiber/recipes), the documentation (https://docs.gofiber.io/) and the articles on the home page in the media section(https://gofiber.io/)
![image](https://user-images.githubusercontent.com/7063188/135213874-f4359526-010f-481e-8613-73ea57ebcb2a.png)

**Comment by 1534854467** [comment]
thanks for your reply!

For example rabbitmq ,it has to call API `/send?msg=text` to trigger router handler and get and publish msg to message queue in handler func

so  must has an another process or goroutine do this flow:
subscribe message queue-> get a message from channel -> call API `/send?msg=message` -> get response or error  -> publish response to message queue

has problems with this approach？or this is a inapposite approach?

**Comment by ReneWerner87** [comment]
do not quite understand

the fiber route only receives the action and then creates a message on the queue by publishing the message

at the same time you need a consumer somewhere for the queue, usually called a worker, which receives the message and then does your action

depending on that a service per rest can happen in the action again, even itself if you use 127.0.0.1 as address
or a database item is created or something else is done

but the concept is completely independent from fiber, so there is no need for support there either

**Comment by 1534854467** [comment]
can I push/get message to fiber ctx queue without call rest api？

I will create a goroutine to subscribe/publish rabbitmq message queue,  then push/get message to fiber ctx queue instead of  call api(127.0.0.1:3000/send).

has any guide？

**Comment by mikeychowy** [comment]
> can I push/get message to fiber ctx queue without call rest api？
> 
> I will create a goroutine to subscribe/publish rabbitmq message queue, then push/get request message to fiber ctx queue instead of call api(127.0.0.1:3000/send).
> 
> has any guide？

It seems you're still misunderstanding event-driven concept.
Let's not talk about edge cases and talk about how most applications will implement this first. (yes, even in java/php/lua/c++ or any other languages, for the most part).

In most cases, the "event " that is referred to by event-driven is actually just a message to a queue forwarded by a HTTP call.
For example, you have an e-commerce site. Let's say you decided to design it with micro-services architecture, you split its functionalities to different services so it's easier to maintain, etc.

Let's say within those services, there's an "order" and "payment" services, and they already talk to each other through http call, a customer places an order, order service saves it as a record in a database. Example route for this would be a POST request to http://example.com/order

The customer then decided to actually go through with the order and would like to pay for it, the order service then pull out the record from database using an identifier (maybe an id, maybe a code) and then forward that order's payment details to payment service to be processed. Example route for this would be a PUT request to http://example.com/order followed by a call to POST request http://example.com/payment inside the order route's handler function.

Now, because HTTP calls are expensive, not real-time, and unreliable at times, you'd like to implement event-driven architecture to these two services, how would we go about doing this?

Firstly, change how the payment service works, no longer would it need to respond to HTTP calls, all routes leading to it can be removed, instead, you now have a long-running worker/handler/controller that's just "listening" (looping) a message queue, any time a specific message is published/pushed/created (a payment "event") on that message queue, the aforementioned worker/handler/controller would respond by processing that payment, maybe it needs to call 3rd party services like a payment gateway or a bank and after that logs the successful/failed payment to database or maybe published/pushed/created a separate specific message on the queue again .

Secondly, on the order service part, very little changes are needed, its POST route doesn't need to be changed because it just creates a record on the database. Its PUT route however, instead of calling /payment like before, now published/pushed/created a specific message (payment "event") to the queue with the needed details, and returns success (HTTP 200 OK) immediately after the "event" was published/pushed/created.

But, wait! you said.
"How would we handle the errors that are bound to happen after doing this? in the old scheme we can just handle it inside order service PUT route, since there is something that is actually given back by payment service that was called.
Now the new scheme is sort of "asynchronous", and I'm confused on that part."

Well, let me tell you this first, there's a million of ways of handling it, and I'm not an expert on that, hell, I'm barely an expert on anything, I barely got graduated from code monkey this year to someone who actually takes part in designing an application.
But I can tell you how i would handle that (in a maybe not so elegant or aligned with best practices kinda way). So, HTTP 200 OK only (mostly, since queues rarely fails) from PUT route of order service right? Well, the front-end can then redirect the customer to a separate page where their payment status of the order would be displayed there, or maybe we can just notify the customer through in-app/email notifications if their payment was successful or not.

If you still have difficulties finding guides/tutorials/examples on this, specifically using go (which is understandable, since it's a relatively new language), I suggest you try reading guides/tutorials/examples on other older languages that you understand and try to translate it into go.
