### ISSUE TITLE
🐛 Getting param when question mark is escaped the param will contain the query as well.

### ISSUE THREAD

**Issue by nicufk** [gofiber/fiber#1626]
**Fiber version**
v2.22.0

**Issue description**
If the request is of form ```http://localhost:8088/v1/scripts/script-name%3Fnamespace=testkube``` when getting the script-name using [Params()](https://pkg.go.dev/github.com/gofiber/fiber/v2@v2.22.0#Ctx.Params) function the script name is "script-name%3Fnamespace=testkube"

**Code snippet**

```go

//server
scripts := s.Routes.Group("/scripts")
scripts.Delete("/:id", s.DeleteScript())

//handler
// DeleteScript for deleting a script with id
func (s testkubeAPI) DeleteScript() fiber.Handler {
	return func(c *fiber.Ctx) error {
		name := c.Params("id")
		namespace := c.Query("namespace", "testkube")
		err := s.ScriptsClient.Delete(namespace, name)
		if err != nil {
			if errors.IsNotFound(err) {
				return s.Error(c, http.StatusNotFound, err)
			}

			return s.Error(c, http.StatusBadGateway, err)
		}

		return c.SendStatus(fiber.StatusNoContent)
	}
}
```

**Comment by ReneWerner87** [comment]
I don't understand the problem, how should it behave? If the control characters separating the url and the query parameters are not marked as such, then the separation does not work either

**Comment by ReneWerner87** [comment]
The control characters #, & and ?
Should not be coded if they are supposed to control something

If you have e.g. a parameter which contains a url with query parameters, this url can be encoded completely, so that the parameter is decoded again at the receiver and can be used completely, but this concept is only valid for the parameters and url parts which you want to pass on.
