### ISSUE TITLE
🐛 ctx.Params() can't Parse correctly

### ISSUE THREAD

**Issue by r6c** [gofiber/fiber#1634]
**Fiber version**
Fiber v2.22.0
**Issue description**
When i try `curl http://127.0.0.1:3000/api/domains/http://google.com/`. ` ctx.Params("domain")` can't parse `http://google.com/`
**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  app.Get("/api/domains/:domain", func(ctx *fiber.Ctx) error {
		source := ctx.Params("domain")
                fmt.Println(source)
                return true;
  }

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
correct the parameter can't be found like this, because this parameter contains the important separator for separating the url parts and therefore you should encode this parameter url and decode it again when you receive it

request with url encoded parameter:
http://localhost:3000/api/domains/http%3A%2F%2Fgoogle.com%2F


or you can use the wildcard parameter, which looks for the first part and then just uses the rest
```go
func main() {
    app := fiber.New()
    app.Get("/api/domains/*", func(ctx *fiber.Ctx) error {
        source := ctx.Params("*")
        fmt.Println(source)
        return nil
    })

    log.Fatal(app.Listen(":3000"))
}

```

**Comment by ReneWerner87** [comment]
@r6c

**Comment by r6c** [comment]
thanks for reply. Now I use `ctx.Query()` instead of `ctx.Params()` to resolve that.
