### ISSUE TITLE
🤗 About fiber.App.Shutdown

### ISSUE THREAD

**Issue by ly020044** [gofiber/fiber#1655]
**Question description**
Run the code and access to http://localhost:3000, Run command `Ctrl+C`. But fiber app is not shutdown, 
`Server exiting`  after access to http://localhost:3000 twice. 

Shouldn't the Shutdown method shut down the app? Why can I continue to visit?

**Code snippet** 
```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.SendString("home page.")
	})

	go func() {
		if err := app.Listen(":3000"); err != nil {
			fmt.Println(err)
			os.Exit(255)
		}
	}()

	quit := make(chan os.Signal)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	if err := app.Shutdown(); err != nil {
		log.Fatal("Server forced to shutdown:", err)
	}

	log.Println("Server exiting")
}
```

**Comment by ReneWerner87** [comment]
Thanks for the report, we will check.

**Comment by ReneWerner87** [comment]
@ly020044 
```go
    quit := make(chan os.Signal, 1)
```
problem was that you did not specify the length of the channel, you should only wait for the first sigterm for the channel

the way you wrote it without the number, the channel waits for more signals, so the whole thing is pending

**Comment by ly020044** [comment]
I have gotten the sign to quit and print `Shutting down server...` in terminal, But you can still visit `http://127.0.0.1:3000`, Print the `Server exiting` to the terminal after accessing twice.

**Comment by vecpeng** [comment]
@ly020044 
May be the annotation of App.Shutdown() helps you:
> Shutdown gracefully shuts down the server without interrupting any active connections. Shutdown works by first closing all open listeners and then waiting indefinitely for all connections to return to idle and then shut down.
Make sure the program doesn't exit and waits instead for Shutdown to return.
Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0.

I guess when you access to http://localhost:3000, the connection from client to server carried a header of connection: keep-alive, so the Shutdown method didn't shutdown the connection.

But sorry for my poor knowledge of network and http, I am not sure why server exited after access to http://localhost:3000 twice.
It may because the new connection close old connection(?

**Comment by rapita** [comment]
You can try using ReadTimeout. 

Example:
```
	app := fiber.New(fiber.Config{
		ReadTimeout: 5 * time.Second,
	})
```

Then termination will be forced after 5 seconds.

**Comment by ly020044** [comment]
@ReneWerner87 @vecpeng @rapita Thanks for reply, Maybe i can force the end.
