### ISSUE TITLE
🤗 Is there a way to unmarshal struct from request info

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#1664]
**Question description**

I'm try to validation request, but I'm using both query and path and some other way like header and body.

**Code snippet** 
```go
type Req struct {
	ID        int    `validate:"gt=0" req:"path"`
	Token     string `req:"header"`
	SomeThing string `req:"body"`
}

func serialize(c *fiber.Ctx, s interface{}) error {
	return nil
}

func (h *handler) getPerson(c *fiber.Ctx) error {
	var r = &Req{}

	err := serialize(c, &r)
	if err != nil {
		return fiber.ErrBadRequest
	}
}
...
	router.Get("/persons/:id", h.getPerson)
...
```

It would be very convenient that I can unmarshal request info and use the same struct to validate it.

**Comment by ReneWerner87** [comment]
there is the queryParser and the bodyParser, you can use both and validate them afterwards, this should also work with the same object, the parsers only need the anotation with the names at the propertie of the structs

the resource parameter is not taken into account, you would have to transfer it manually

i can't think of a way to write a function that could merge the resource parameters and the parameters of the request methods, so that you have a nice clean result

most users don't need this function either, mostly one or the other, depending on which CRUD methods are used


if you have some ideas, you are welcome to come to us with a concept or better a pull request

**Comment by ReneWerner87** [comment]
@Trim21

**Comment by Trim21** [comment]
Thank you
