### ISSUE TITLE
🤗 Why gofiber.io is banned in india?

### ISSUE THREAD

**Issue by joey00072** [gofiber/fiber#1703]
**Question description**
![image](https://user-images.githubusercontent.com/35176826/148819143-967c485b-3e0e-457f-a14d-84512b82ff82.png)

23:58 10 jan 2022 UTC+5:30

**Comment by hi019** [comment]
What about https://docs.gofiber.io ?

**Comment by joey00072** [comment]
![Screenshot (19)](https://user-images.githubusercontent.com/35176826/148822894-341a8ffd-2dd9-4666-81c9-01e01641162d.png)
 Working

**Comment by venkatesh-nagineni** [comment]
I can access both https://gofiber.io/ and https://docs.gofiber.io/

**Comment by ReneWerner87** [comment]
> I can access both https://gofiber.io/ and https://docs.gofiber.io/
thanks for checking, since you are also in india, it means it is not blocked for all of india


@joey00072 unfortunately we can not do anything if the government of your country partially blocks these urls

since it is only the start page and not the documentation page i don't see this as too critical either

other possible solutions would be to try another dns or vpn

**Comment by ReneWerner87** [comment]
similar issue: https://github.com/gofiber/fiber/issues/1483
