### ISSUE TITLE
🤗 how to get context.Content() and context.Body() when after connection return ?

### ISSUE THREAD

**Issue by yellowmarlboro** [gofiber/fiber#1706]
**Question description**
my handle start a goroutine and then return 200. how to get context in the goroutine ?
**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  app.Get("/some", func (c *fiber.Ctx) error {

	resp := Response{}

	go func() {
		err := MainFlow(newFlow, f, processFunc)
		if err != nil {
			sentry.ErrorHandle(c, err)
		}
	}()

	return c.Status(200).JSON(resp)
})
}
```
i tried use context in **ErrorHandle** , and in the function i use **c.Content()** and **c.Body**, then panic cause **invalid memory address or nil pointer dereference**, i found a lot of info lost in context.

have a good way to do that ? thanks~

**Comment by ReneWerner87** [comment]
> i tried use context in ErrorHandle , and in the function i use c.Content() and c.Body, then panic cause invalid memory address or nil pointer dereference, i found a lot of info lost in context.

yes, that is right, because when the response has been sent, the memory areas of the request and the response are released again.

if you need data of the request inside your go function, you have to create a copy of the data

to provide tremendous performance, fasthttp uses under the hood the concept of reusing memory from previously created objects

**Comment by yellowmarlboro** [comment]
got it. i'll create a copy of the data, thank you very much !
