### ISSUE TITLE
🤗 Which context to use to detect client disconnected? 

### ISSUE THREAD

**Issue by bofeng** [gofiber/fiber#1718]
**Question description**

I have a demo handler like below, and used `curl` to send the request. If in the process I press ctrl-c to quit the curl (client disconnected), the server will still print "ticker", the "client quit" case will never be triggered:

**Code snippet** _Optional_

```go
func hello(c *fiber.Ctx) error {
	ticker := time.NewTicker(1 * time.Second)
	for i := 0; i < 10; i++ {
		select {
		case <-c.Context().Done():
			fmt.Println("client quit")
		case <-ticker.C:
			fmt.Println("ticker")
		}
	}
	return c.SendString("hello")
}
```

I thought that use the `c.Context().Done()` in `fiber` could listen on the "client disconnect" case, but it wasn't triggered. And I know in `gin` you can listen to `c.Request.Context().Done()`, such that if the client disconnected, this case will be triggered properly. 

So did I use the wrong context.Done() to listen to? which context should I use for such case in `fiber`?

**Comment by DarthBenro008** [comment]
@bofeng , Unfortunately, `fasthttp` does not determine or support the detection of client connection as mentioned here: 
https://github.com/valyala/fasthttp/issues/468#issuecomment-439665014

Naturally, GoFiber won't have such context support because the Context of GoFiber is wrapped around fasthttp. 


Hope this answers your query, closing this issue, if you still have doubts, feel free to re-open the issue or join us on discord to have a discussion on the same with community! 😄
