### ISSUE TITLE
🐛 memory leak

### ISSUE THREAD

**Issue by 547372621** [gofiber/fiber#1724]
**Fiber version**
use v2.24.0

**Issue description**
memory leak

**Code snippet**

start server
```go
import (
	"bytes"
	"github.com/gofiber/fiber/v2"
	"net/http"
	_ "net/http/pprof"
)

func main() {
	go func() {
		err := http.ListenAndServe(":6000", nil)
		if err != nil {
			panic(err)
		}
	}()
	app := fiber.New()

	app.Get("/test", func(c *fiber.Ctx) error {
		buffer := bytes.NewBufferString("")
		for i := 0; i < 1000000; i++ {
			buffer.WriteString("123")
		}
		return c.Send(buffer.Bytes())
	})

	if err := app.Listen(":9001"); err != nil {
		panic(err)
	}
}
```

run client 5 seconds , after 60 seconds , run pprof

the memory has not been released

```go
package main

import (
	"fmt"
	"net/http"
	"sync"
	"time"
)

func main() {

	for i := 0; i < 500; i++ {

		go func() {
			client := http.Client{}
			for {
				response, err := client.Get("http://localhost:9001/test")
				if err != nil {
					fmt.Println(err)
					continue
				}

				for {
					b := make([]byte, 1)
					_, err = response.Body.Read(b)
					if err != nil {
						break
					}
					time.Sleep(time.Second)
				}
			}

		}()
	}
	group := sync.WaitGroup{}
	group.Add(1)
	group.Wait()
}

```

```
go tool pprof http://localhost:6000/debug/pprof/heap
```

![image](https://user-images.githubusercontent.com/19144018/150370996-5cba9674-dd5a-474d-a944-9d990d931cff.png)

**Comment by ReneWerner87** [comment]
what do you expect ? @547372621 

isn't the problem that you only load one byte at a time from the enormous response and then always wait a second and then the process starts over again? should the server already release the memory?

if you really found a memory leak here, then please create the report in the fasthttp project, because we use the core without any customizations for this behavior
https://github.com/valyala/fasthttp

**Comment by 547372621** [comment]
The problem is that after I close the client process, the server memory is still not released

**Comment by ReneWerner87** [comment]
@547372621 can you create an issue at fasthttp, with the fasthttp equivalent of the code from fiber for this example

i think this should be doable, otherwise let me know and i will try to help

not 100% sure yet if this is really a problem or the connection is not closed properly clean according to the standard workflow and therefore fasthttp is still holding the data for a short time

**Comment by ReneWerner87** [comment]
@547372621 any progress ?
