### ISSUE TITLE
🐛 NewErrrors() returns error array

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1727]
@vecpeng did you really test it ? Fiber's router's handler returns just error not []error.

**Comment by vecpeng** [comment]
Sorry, maybe there is a misunderstanding about #1695.

I just thought that it maybe not a good idea to use interface{} instead of string to represent an error because the [error](https://pkg.go.dev/builtin#error) in go, indeed, is a string. Moreover, it might introduce backward compatibility issues if someone uses `e.Message`.
So I just want to add a way to deal with multiple errors in array but it seems haven't been well considered and still should
be discussed. I'm sorry for that.

**Comment by balcieren** [comment]
@vecpeng if you want to examine and support you can look PR #1728
