### ISSUE TITLE
🤔 Question on versioning

### ISSUE THREAD

**Issue by alex-shpak** [gofiber/fiber#179]
Hi!

I thought to give a try to `fiber` and make small app, and at this point I'm confused about versioning. Seems like there was versions prior `1.0.0` and between `1.0.0` and `1.7`, like in TechEmpower benchmarks mentioned [`0.8.0`](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Go/fiber#version-tested), and also for example [`1.0.1`](https://github.com/gofiber/fiber/issues/159#issuecomment-589773378) and [`1.5.0`](https://github.com/gofiber/fiber/issues/136#issue-564378850), [`1.6.0`](https://github.com/gofiber/fiber/issues/129#issuecomment-585565469) and so on.

https://pkg.go.dev/github.com/gofiber/fiber?tab=versions
But these versions are not tagged in git repository. Where did they go/come from? 

I think it might be dangerous to remove or even tag another commit with same version. Considering introduction of `GOPROXY` there might be caching proxy servers for go modules. Also it might affect checksums at https://sum.golang.org/.

**Comment by Fenny** [comment]
Fiber was in `beta` for a while and when we decided to come with an official release we didn't want to jump to v2. Resetting to `v1.0.0` without pre-release didn't workout because like you said, GOPROXY cached all other releases. This forced us to continue with `1.7.x`+ for versioning.

All older versions are still available via `go get github.com/gofiber/fiber@v.v.v`

**Comment by alex-shpak** [comment]
Good to know! Thank you for your reply.
