### ISSUE TITLE
🤗 curl upload files without headers 

### ISSUE THREAD

**Issue by webdevium** [gofiber/fiber#1867]
**Question description**
I'm beginner in fiber and golang. And sorry if question is stupid.

How can I get all uploaded files which I upload using
```
curl -T test1.file -T test2.file localhost:3333
```

Every time I receive **request has no multipart/form-data Content-Type**

And this is reasonable: there are no headers :)

Is there any method to avoid headers checking and collect all uploaded files?

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
)

func main() {

	app := fiber.New()
	app.Put("/*", func(ctx *fiber.Ctx) error {
		form, err := ctx.MultipartForm()
		if err != nil {
			return err
		}

		log.Println(form.File)

		return nil
	})

	app.Listen(":3333")
}

```

**Comment by ReneWerner87** [comment]
Unfortunately no. 

In most frameworks/programing languages it is important to send the content type with the upload of files or also with the post body(form, xml, json...) , so that the framework knows how to interpret the content of the request body and how this can be done best.

Since we build on fasthttp and this is a requirement in any case, you have to send it in the case.

Didn't check the RFC standard, might even be written there

**Comment by webdevium** [comment]
@ReneWerner87 
Tnx!
