### ISSUE TITLE
How to bind array of query params to slice of struct

### ISSUE THREAD

**Issue by ChandanChainani** [gofiber/fiber#1868]
**Question description**
How to bind array of query params to slice of struct
```
curl -X GET "http://localhost:3000/?person[name]=john&person[pass]=doe"
```

**Code snippet**

```go
package main

import (
    "log"
    "github.com/gofiber/fiber/v2"
)

type Person struct {
  Name string `query:"name" json:"name" xml:"name" form:"name"`
  Pass string `query:"pass" json:"pass" xml:"pass" form:"pass"`
}

func main() {
  app := fiber.New()
  app.Get("/", func(c *fiber.Ctx) error {
    persons := []Person{}

    if err := c.QueryParser(&persons); err != nil {
      return err
    }

    // log.Println(persons[0].Name)     // john
    // log.Println(persons[0].Pass)     // doe
    log.Println(persons)

    log.Println()
    return c.SendString("Get Called")
  })
}
```

**Comment by ReneWerner87** [comment]
In your example you have exactly one person in the query parameters, but a list of persons in the code.

Which side is wrong, do you expect more than one person? Then you have to structure the parameters differently.
Or only one person? Then you have to adapt the passing to the queryparser method.
By the way, for the first levels where person appears you also need eib struct, so that the key can be applied to an object and mapped correctly.

**Comment by ChandanChainani** [comment]
@ReneWerner87 For example I just created single person but I want it to process as many person are passed in query parameters either it would be one person or many persons.

**Comment by ReneWerner87** [comment]
then you should just always use the pattern for the more number of people, because then it is possible to transfer one or more

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

// query: curl -g -X GET "http://localhost:3000/?persons[0][name]=john&persons[0][pass]=doe"

// recommendation -> name of the api and parameters
type ApiParameters struct {
	Persons []Person `query:"persons" json:"persons" xml:"persons" form:"persons"`
}
type Person struct {
	Name string `query:"name" json:"name" xml:"name" form:"name"`
	Pass string `query:"pass" json:"pass" xml:"pass" form:"pass"`
}

func main() {
	app := fiber.New()
	app.Get("/", func(c *fiber.Ctx) error {
		parameters := ApiParameters{}

		if err := c.QueryParser(&parameters); err != nil {
			return err
		}

		log.Println(parameters.Persons[0].Name) // john
		log.Println(parameters.Persons[0].Pass) // doe
		log.Println(parameters)

		return c.SendString("Get Called")
	})

	log.Fatalln(app.Listen(":3000"))
}

```
![image](https://user-images.githubusercontent.com/7063188/164387491-22862455-52b9-43e9-b614-e7fdc0a4d5e4.png)

![image](https://user-images.githubusercontent.com/7063188/164387468-8416fd16-462d-41bb-8024-6237ea445796.png)

**Comment by ReneWerner87** [comment]
@ChandanChainani

**Comment by ChandanChainani** [comment]
@ReneWerner87
Thank you very much  :clap: :clap: :clap:  

Is it possible to with only 1 struct instead of maintaining 2 struct?

**Comment by ReneWerner87** [comment]
Not sure, but I think no.
