### ISSUE TITLE
🤗  Automatically parse the body ?

### ISSUE THREAD

**Issue by RabieAli95** [gofiber/fiber#1937]
Hi there,
Is there any way to parse the body of the request automatically, instead of doing this `if` in each handler!

```
if err := c.BodyParser(&post); err != nil {
    // do something
}
```

**Comment by ReneWerner87** [comment]
Because golang is a strongly typed language and you should create a struct for better use in the following processes I would not recommend this.

There are possibilities, you could e.g. make a middleware with app.Use with the filter criterion on an existing body and in there, parse the body on a fiber.Map, put it in the locals and use it later or just use the ctx.Body method, but then you have no idea about the content and the basic structure.
