### ISSUE TITLE
Issue while routing🐛 

### ISSUE THREAD

**Issue by ITheCorgi** [gofiber/fiber#1952]
**Fiber version**
v2.34.1
**Issue description**
I have an a router definition (see code snippet).  I faced an issue that I cannot call a method by uri `GET "/api/v1/somethings/check"`, because fiber routes it at `GET "/api/v1/somethings/:id"`
The only one solution in this case is to pop up check method in a stack right before get by id method, like:
```
app.Get("/api/v1/somethings/check", checkSomething(someService))
app.Get("/api/v1/somethings/:id", getSomething(someService))
```
Fiber server configuration uses default config with disabled startup message

**Code snippet**

```
func NewRouter(app fiber.Router, someService interface{}) {
	app.Post("/api/v1/somethings", addSomething(someService))
	app.Get("/api/v1/somethings", listSomething(someService))
	app.Get("/api/v1/somethings/:id", getSomething(someService))
	app.Get("/api/v1/somethings/check", checkSomething(someService))
}
```

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/guide/routing#paths

![image](https://user-images.githubusercontent.com/7063188/176362512-abc94e92-800b-4c0a-b537-917ee5f02f43.png)

this is not a mistake but expected behavior

as in expressjs the order of route declarations matters and the less specific route will always match before the specific route

https://github.com/gofiber/fiber/issues/1090#issuecomment-751335790
https://github.com/gofiber/fiber/issues/1088#issuecomment-750476089
https://github.com/gofiber/fiber/issues/1469#issuecomment-892930189
