### ISSUE TITLE
🐛 [Bug]: Mounting does not work if you use it before declaring the route

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#2066]
### Bug Description

I found critical bugs about mount. 

1.  If app's router codes (Get, Post, ...) write after `app.Use()`, app wouldn't register route stack.
```go
func main() {
	app := fiber.New()
	sub := fiber.New()

	app.Mount("/sub", sub)

	sub.Get("/", func(c *fiber.Ctx) error {
		return c.JSON("this is sub app")
	})

	app.Listen(":3000")
}
```
2. Sub in sub mounting does not work
```go
func main() {
	app := fiber.New()
	sub := fiber.New()
	sub2 := fiber.New()
	sub2.Get("/", func(c *fiber.Ctx) error {
		return c.JSON("this is sub2 app")
	})

	app.Mount("/sub", sub)

	sub.Mount("/sub2", sub2)

	app.Listen(":3000")
}
```

### Expected Behavior

Application should register sub app's stack in `app.Listen()`  (`startupProcess()`)

need good refactor and fix bugs

### Fiber Version

v2.37.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
```go
func main() {
	app := fiber.New()
	sub := fiber.New()

	sub.Get("/", func(c *fiber.Ctx) error {
		return c.JSON("this is sub app")
	})
	app.Mount("/sub", sub) // <- must be at the end

	log.Fatal(app.Listen(":3000"))
}
```
the current implementation takes the route at the time of the mount command and transfers it to the parent app

just as the order of routes is important in the declaration of routes, it is also important here

probably we could also change this and only pull the routes from the sub app in the startup process
(but would remove the "critical" part of the bug, as it is a known intentional behavior)

```go
func main() {
	app := fiber.New()
	sub := fiber.New()
	sub2 := fiber.New()
	sub2.Get("/", func(c *fiber.Ctx) error {
		return c.JSON("this is sub2 app")
	})

	sub.Mount("/sub2", sub2) // <- first mount sub2 in sub
	app.Mount("/sub", sub) // <- then mount sub in app

	log.Fatal(app.Listen(":3000"))
}
```
same with the 2nd example 

here must be muted in the sequence

maybe we should only register the app in the parent app at the time of mounting and go through recursively at startup process
but i don't know if this will have negative effects later, because after this command you actually think that something is transferred that wasn't transferred yet
-> if for example a sub app is mounted in the app and in this app already a hook is defined on a route of the sub app, but this route is not yet transferred, because we move this process to start

maybe you should also transfer multiple times? at the time of mounting and later when starting the server if something else has been added

help with a pull request is welcome

**Comment by ReneWerner87** [comment]
@wangjq4214 
> but i don't know if this will have negative effects later, because after this command you actually think that something is transferred that wasn't transferred yet
-> if for example a sub app is mounted in the app and in this app already a hook is defined on a route of the sub app, but this route is not yet transferred, because we move this process to start

what do you think about this problem ?

**Comment by balcieren** [comment]
@ReneWerner87 and @wangjq4214 , this problem was resolved on v3-alpha branch. Solution: Router stacks should be registered on startupProcess. [see also](https://github.com/gofiber/fiber/blob/v3-alpha/core.go#L379)

**Comment by ReneWerner87** [comment]
> @ReneWerner87 and @wangjq4214 , this problem was resolved on v3-alpha branch. Solution: Router stacks should be registered on buildTree. [see also](https://github.com/gofiber/fiber/blob/v3-alpha/core.go#L379)

good to know, but we are still quite a way away from version3 and maybe wanted to solve it already in version2

**Comment by balcieren** [comment]
> 

we can do this for v2, [see also](https://github.com/gofiber/fiber/blob/master/app.go#L593-L598) we should write this lines on buildTree

**Comment by ReneWerner87** [comment]
Yes of course but that does not help me answer my question

If you add the routes later and then add hooks that work when the route is registered, it can be quite unexpected for the user.
