### ISSUE TITLE
🤗 [Question]: Will support generic in next version?

### ISSUE THREAD

**Issue by goldwind-ting** [gofiber/fiber#2126]
### Question Description

The `golang` had supported generic, so will fiber support generic in next version?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
We are currently heavily dependent on your help (community) in the development of the new version. Since we use golang 1.18 we can of course avert this, the question is only with which functions. 

So if you have ideas or suggestions feel free to create a comment or pull request and we will decide in the group.
