### ISSUE TITLE
document error

### ISSUE THREAD

**Issue by hagbei** [gofiber/fiber#2192]
[https://docs.gofiber.io/api/ctx#isfromlocal](url)

```
func (c *Ctx) IPs() []string
```

**Comment by ReneWerner87** [comment]
issue was closed because it does not comply with the guidelines and contains too little information

**Comment by ReneWerner87** [comment]
Thanks for the hint, I think you meant that the signature in the documentation is wrong
https://github.com/gofiber/docs/commit/a52cd0ce4bd8b0b3b2ba77a730e3e07d61de77f7

but please next time just write, otherwise I have to interpret things that sometimes do not correspond to the thoughts of the creator
