### ISSUE TITLE
🤗 [Question]: How to disable color in fiberLogger

### ISSUE THREAD

**Issue by Dalakoti07** [gofiber/fiber#2372]
### Question Description

I am creating fiberLogger with the following configs, I want to disable color because I am writing these logs in .log file.

What are the ways I can achieve this?

Moreover `enableColors`  in config.go is not exported.

### Code Snippet (optional)

```go
loggerConfig := fiberLogger.Config{
		Format: "${url} ${latency} ${status}",
		Done: func(_ *fiber.Ctx, logString []byte) {
			logger.LogDebugMessage(fmt.Sprintf("%s", logString))
		},
	}
```
```


### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
yes currently the user has no possibility to influence it

if there is the possibility to use the colors they will be played, enableColors is currently only available internally

we could make it available as a feature

but it would be more than just exposing the property, you would have to reverse it, since false is the default of all booleans
and rebuild a bit

**Comment by Dalakoti07** [comment]
Thanks @ReneWerner87 for reply

Is anyone working on this? 

Or Can I pick this up?

**Comment by ReneWerner87** [comment]
sure you can work on this (thx)

**Comment by ReneWerner87** [comment]
@Dalakoti07 any progress ?

**Comment by Dalakoti07** [comment]
Hi @ReneWerner87, I got occupied my some other work. Can you please assign it to someone else?

**Comment by ReneWerner87** [comment]
We will have a look at it on Sunday

**Comment by Vickko** [comment]
I thought about this question a little further today, and realized that simply exposing the property is indeed flawed.
So I came up with a new plan:
-  Keep `enableColors` unchanged, add a new property `DisableColors` instead.
 - If a user pass custom config into logger, there is no straightforward way to assign `true`  as default value for `enableColors` without being overwritten by the deafult `false` for bool.
 - I've considered refactoring config using getters and setters, but that would break backward compatibility.
 - Meanwhile, users may want to disable color only when log is heading towards a file, or other processing program. In this case, they may want to disable it explicitly.
- So on the basis of the original logic, if `DisableColors` is assigned `true`, it means they want `enableColors = false`.
- By doing so, we can keep the original code changes to a minimum.
#####  Points awaiting improvement：
1. Property names `DisableColors` and `enableColors` appear in the same place might be confusing. Maybe one of them should be renamed.
2. In the original question, Dalakoti07 wants to pass the `logString` to his own logger in `Done` function, in order to write log into file. This means log will still be outputted to terminal. I'm assuming log on terminal still needs color, while log passed to his own logger dont.
3. Both `New()` and `configDefault()` take `config ...Config` as arguments, but currently only process the first one. Considering this point along with point 2, maybe it's supposed to generate different outputs for each config in the future plan? Although let fiber `use()`  multiple loggers with different config can achieve a similar effect, it seems to harm performance.

Anyway, `DisableColors` can solve the problem temporarily, and I'm still thinking about the points mentioned above. I'm looking forward to hearing your opinions!

**Comment by Skyenought** [comment]
pls assign me, i will make PR later
