### ISSUE TITLE
🐛 [Bug]: CORS errors

### ISSUE THREAD

**Issue by jney** [gofiber/fiber#2389]
### Bug Description

updating fiber version generate a lot of CORS issue on the frontend.

```diff
- github.com/gofiber/fiber/v2 v2.42.0
+ github.com/gofiber/fiber/v2 v2.43.0
```

### How to Reproduce

don't know

### Expected Behavior

no cors error

### Fiber Version

v2.43.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
unfortunately, without a description of the problem and an example, we can do nothing

**Comment by ReneWerner87** [comment]
maybe its related to https://github.com/gofiber/fiber/pull/2339 

but without an observation report or other information we can unfortunately do nothing

**Comment by jney** [comment]
Hi @ReneWerner87, I didn't find out what was the exact cause. But it happens on the frontend so I need to identify the problematic header.
And yes rolling back to `v2.42.0` just make it work

**Comment by ReneWerner87** [comment]
@ryand67 can you support here

**Comment by ryand67** [comment]
@ReneWerner87 I'm out recovering from a surgery so it may be a week or so before I can really commit much time. And I had tested and it seemed to be working on my tests I had run. I'll try and get on and figure it out but may be a minute.

**Comment by jney** [comment]
```diff
- < Access-Control-Allow-Origin: *
+ < Access-Control-Allow-Origin: 
```

> what do you mean by this?

Header changed

- `v2.42.0`: Access-Control-Allow-Origin: *
- `v2.43.0`: Access-Control-Allow-Origin:

**Comment by ReneWerner87** [comment]
yes that's what I thought, just wanted to have a little more context because I can not understand it in my case

in the browser, in postman ? how is the request ? or the origin header ?

**Comment by Jamess-Lucass** [comment]
@jney Are you able to provide the code in your project where you're defining the fiber cors config.

I recently ran into a cors issue while upgrading fiber and was a result of the issue https://github.com/gofiber/fiber/issues/2338 with the PR @ReneWerner87 posted above.

You may be running into the same issue as you're using `Access-Control-Allow-Credentials: true` and I am assuming you were utilizing something similar to
```
cors.Config{
    AllowOrigins:     "*",
    AllowCredentials: true,
} 
```
where previously this would have worked due to how fiber were handling setting the response header for this.

If this does seem familiar then you may either specify the origins explicitly in the `AllowOrigins` property or I have opened a feature issue https://github.com/gofiber/fiber/issues/2390 to see if implementation a func where we are able to perform some conditional to set the `Access-Control-Allow-Origin` to the origin.

Again, reiteration the above is speculation, like others have suggested if you're able to provide code/examples where someone is able to replicate the issue then you're going to receive answers.

**Comment by ReneWerner87** [comment]
i was just using the config from the comment
https://github.com/gofiber/fiber/issues/2389#issuecomment-1486996090

```go
cors.Config{
    AllowOrigins:     "*",
    AllowCredentials: true,
} 
```

what should have led to the problems here ? would be good if someone shows me how the error looks like, without knowing what the observation of the error is, its very hard for me to help

**Comment by jney** [comment]
Maybe I am wrong, but [this](https://github.com/gofiber/fiber/pull/2339/files#diff-e0ba382753d860a1818f6b4780289ead3588be55993298e2c1ee91e175007229L115-R116 ) is wrong
As far as I remember when the `AllowCredentials` is set, `Access-Control-Allow-Origin` must be explicit, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by ReneWerner87** [comment]
can we help otherwise ? otherwise I would close the issue
