### ISSUE TITLE
🚀 [Feature] Middleware to support Kubernetes probes

### ISSUE THREAD

**Issue by x80486** [gofiber/fiber#2457]
### Feature Description

Applications deployed on `Kubernetes` should provide information about their internal state with [Container Probes](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes).

`Fiber` could make use of a middleware to automatically manage the application availability state, so when deploying in `Kubernetes` (or any other environment) there is a built-in option for gathering the "liveness" and "readiness" information.

This could be as simple as implementing the aforementioned probes, but it can plug as well in the application's lifecycle; for instance, refusing traffic automatically when starting. etc. — but that could be phased out, if relevant, into another unit of work.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
middlewares that are in the core are not technology specific

you can implement a health check like this

![image](https://github.com/gofiber/fiber/assets/7063188/423e2ee4-e86b-4d03-bcf1-98752c28d6a2)
![image](https://github.com/gofiber/fiber/assets/7063188/eb8a4c12-b9ce-4368-a8a8-f95808a8ad84)

**Comment by x80486** [comment]
I understand this might not be part of the "core" middlewares, but what you are describing is a health-check endpoint, something like what [`go-chi`](https://pkg.go.dev/github.com/go-chi/chi/middleware#Heartbeat) provides by default — if included.

Liveness and readiness fulfill two different scenarios — they shouldn't be mixed up, and their implementation is not as simple as one endpoint for both returning an `HTTP 200 (OK)`.

While this ticket is oriented towards a particular technology, the concepts are general enough to be used in almost any containerized environment.

**Comment by leonklingele** [comment]
Agreeing with @x80486. Let's reopen this.

**Comment by leonklingele** [comment]
@x80486 what do you think of a new readyness middleware which can be configured as follows:

```go
type Config struct {
	// IsLive returns true when the application is running, false otherwise.
	IsLive func(c fiber.Ctx) bool

	// IsReady returns true when the application is running and ready to serve requests, false otherwise.
	IsReady func(c fiber.Ctx) bool
}
```

Exemplary instance:

```go
app.Use(readiness.New(readiness.Config{
	IsLive: func(c fiber.Ctx) bool { return true },

	IsReady: func(c fiber.Ctx) bool {
		return db.Ready() && filesystem.Ready() && ..
	}
}))
```

**Comment by ReneWerner87** [comment]
how would this middleware look like ?
what added value does it bring instead of registering a route for the action which happens in the handler and is very specific?

don't see this middleware currently in the core, if so then maybe in the contribution packet, but i don't see a big added value there currently, because the checks inside will take up most of the code. 

all the middleware could do is to register this code which is injected from outside on a certain route
but this is also very easy to do with the board means of fiber

> Liveness and readiness fulfill two different scenarios — they shouldn't be mixed up, and their implementation is not as simple as one endpoint for both returning an HTTP 200 (OK).

by the way, i am aware of the difference between readiness and liveness probe and the above example was just to show how you can easily accomplish such a thing with the board tools
in the above example, there is also no database or similar dependency in the microservice that needs to be tested

**Comment by gaby** [comment]
Would adding a `heartbeat` middleware that by default returns 200 like the one from `go-chi`, but still allow the dev to override with a custom config the function work?

**Comment by x80486** [comment]
`Fiber` is a "web framework". That means it's predictable to have certain functionality that toolkits and libraries won't. Since `Kubernetes` is the preferred orchestration tool for deploying containers, providing something like this by default will satisfy the need of most users who are looking to implement this — regardless of how easy is to implement. On the other hand, there is limit on the amount of stuff anything can have, and if owners feel this shouldn't be part of `Fiber` it's understandable, because I don't know the framework as well as they do.

Moreover, I understand @ReneWerner87's concern and probably this wouldn't fit in the main set, but on the contributions one.

At the same time, @leonklingele wrote something that's more or less what users will be looking for. Basically, the implementation for _liveness_ could be provided out of the box — and it shouldn't need to be changed because it's straightforward. The difficult one would be _readiness_ because it involves more "moving parts" that only the application in question should be able to implement correctly. Nevertheless, again, what @leonklingele wrote provides a guidance/framework everyone can look at and customize, while having a default implementation.

**Comment by leonklingele** [comment]
Instead of making it a middleware, we could as well introduce those two new fields in the `fiber.Config` struct. It's not middleware functionality, after all..

```go
package fiber

type Config struct {
	// …

	// IsLive should return true when the application is running, false otherwise.
	IsLive func(c fiber.Ctx) bool
	IsLiveEndpoint string // Defaults to /livez

	// IsReady should return true when the application is running and ready to serve requests, false otherwise.
	IsReady func(c fiber.Ctx) bool
	IsReadyEndpoint string // Defaults to /readyz

	// …
}
```

(`IsLive` could be made optional as it solely depends on fiber's HTTP server running state)

Not really required to have it in the fiber stdlib, but it definitely is a nice-to-have as quite commonly used when working with [Kubernetes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes), [Docker](https://docs.docker.com/engine/reference/builder/#healthcheck) or [Docker Compose](https://github.com/compose-spec/compose-spec/blob/620134fb66bce9cddac7b1a23d316347d5887da3/spec.md#long-syntax-1).

**Comment by luk3skyw4lker** [comment]
Is someone working on this or was it already implemented? I would like to take a stab
