### ISSUE TITLE
🤔 confusing version

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#254]
**Question description**

The versions of `fiber` is very confusing.

1.8.431 should be considered newer than 1.8.5.

I got confused once when I upgrade form 1.8.32 to 1.8.4.

as a result:
https://pkg.go.dev/mod/github.com/gofiber/fiber@v1.8.431?tab=versions
![image](https://user-images.githubusercontent.com/13553903/78216395-51b2d600-74ec-11ea-807c-09fc4c934a78.png)

**Comment by Fenny** [comment]
Hey @Trim21, I understand it is confusing but we didn't want to jump to `v2` yet.
The current versioning is implemented as `#major.#minor.#micro#nano#pico`.

It could look like we skipped `388` micro versions since `v1.8.43` but its actually a pico upgrade.

We might ditch this versioning method after `v1.9`, sorry for the confusion.

**Comment by Trim21** [comment]
Thanks for your explanation.
