### ISSUE TITLE
🤗 [Question]: When will the v3 version be released?

### ISSUE THREAD

**Issue by panyox** [gofiber/fiber#2544]
### Question Description

can't wait to try it

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
we do not have a date yet

but we are working on it, we wanted to fix some things in version 2 and clean up the repositories so that the move to version 3 will be easier now

since this is an opensource project and we also have to work on the side, it's a bit slow, so the code and the work is on hold for now 

in the next weeks we will make our TODO list and see what is the status and what is still on the agenda

important is that we don't rush, because you expect a good version 3, so we also wanted to stabilize version 2 first (we see from the requests that it has grown and is stable now)

i will close this issue and we will inform you as soon as we have more info
by starting discussions, posting todo lists, disclosing the roadmap and/or writing blog entries
