### ISSUE TITLE
🤗 [Question]: comparison with bun? (elysia, hono

### ISSUE THREAD

**Issue by terlan4** [gofiber/fiber#2559]
### Question Description

So according to ratio of fiber and elysia with express, does it mean elysia-bun framework and fiber is almost at the same speed?
I would be happy to see benchmarking of bun frameworks(elysia, hono) against go frameworks. Thank you

![image](https://github.com/elysiajs/elysia/assets/138553763/98d34253-cfd0-4d91-9008-a8464803a04c)
![image](https://github.com/elysiajs/elysia/assets/138553763/4e6e1ce9-d3e0-451e-a5d6-67a9631d89e6)
>elysia benchmark source: https://elysiajs.com/

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
benchmarks are always difficult because it varies from machine to machine and in some cases with quite powerful frameworks also the network plays a big role for the performance test. 

if you want to compare these frameworks i would recommend you 2 independent overview sites

the benchmarker which compares different web frameworks independent of the programming language and techempower which has a more accurate and from my point of view even more professional test setup

https://web-frameworks-benchmark.netlify.app/result?f=elysia,fiber,express

https://web-frameworks-benchmark.netlify.app/compare?f=fiber,elysia,express

https://www.techempower.com/benchmarks/#section=test&runid=273fa177-fc53-43a9-a97d-d6f3f2ade99a&test=json

Unfortunately this framework is not yet available on techempower, so you can only compare different frameworks on theBenchmarker.

but i would recommend you to check the frameworks there, maybe someone will add it later

**Comment by gaby** [comment]
@terlan4 The source code they use to test each framework is here https://github.com/the-benchmarker/web-frameworks

**Comment by ReneWerner87** [comment]
will close the report, hope you found your information
otherwise you have to ask the authors of the benchmarks
