### ISSUE TITLE
🐛 [Bug]: `Ctx.GetReqHeaders` doesn't respect multiple fields with same name

### ISSUE THREAD

**Issue by makkes** [gofiber/fiber#2594]
### Bug Description

When calling `Ctx.GetReqHeaders` on a request with this header:

```
"Accept": "text/plain",
"Accept": "application/json",
[...]
```

Then the resulting map contains only the last field value.

See the [relevant RFC section](https://datatracker.ietf.org/doc/html/rfc9110#section-5.2).

### How to Reproduce

1. Run the code snippet from below
2. Run `curl localhost:3000 -H 'Accept: text/plain' -H 'Accept: application/json'`
3. Check the logs of the app

### Expected Behavior

The logs should show the value of both `Accept` fields:

```
map[Accept:application/json,text/plain Host:localhost:3000 User-Agent:curl/8.2.1]
```

### Fiber Version

v2.48.0

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("", func(c *fiber.Ctx) error {
		fmt.Println(c.GetReqHeaders())
		return nil
	})

	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
I think we need to change signature to fix the bug https://github.com/gofiber/fiber/blob/master/ctx.go#L654

Also getrespheaders needs to be fixed, too.

**Comment by makkes** [comment]
I don't think the signature needs to be changed. All the function would need to do is to join all the values using `, ` according to the RFC I linked above:

>  When a field name is repeated within a section, its combined field value consists of the list of corresponding field line values within that section, concatenated in order, with each field line value separated by a comma.

So a header of 

```
Accept: text/plain
Accept: application/json
```

would result in a map with key `Accept` and value `text/plain, application/json`.

**Comment by efectn** [comment]
> I don't think the signature needs to be changed. All the function would need to do is to join all the values using `, ` according to the RFC I linked above:
> 
> > When a field name is repeated within a section, its combined field value consists of the list of corresponding field line values within that section, concatenated in order, with each field line value separated by a comma.
> 
> So a header of
> 
> ```
> Accept: text/plain
> Accept: application/json
> ```
> 
> would result in a map with key `Accept` and value `text/plain, application/json`.

Yes it's also an option but making them slice seems more logical to me. Joining headers might be bad idea for several cases. i.e when i have a comma in header value, it will be difficult to parse it

**Comment by makkes** [comment]
> Yes it's also an option but making them slice seems more logical to me. Joining headers might be bad idea for several cases. i.e when i have a comma in header value, it will be difficult to parse it

RFC 9110 is pretty [specific about this](https://datatracker.ietf.org/doc/html/rfc9110#name-field-values) in demanding that field values that can contain commas need to be quoted. But I agree it can get complicated quickly depending on the individual header field. Go also uses a [`map[string][]string`](https://pkg.go.dev/net/http#Header) so it might be the most reasonable way to follow that example.

**Comment by ReneWerner87** [comment]
![image](https://github.com/gofiber/fiber/assets/7063188/00a0add3-a9fa-49a4-8111-c1c1885274d5)
![image](https://github.com/gofiber/fiber/assets/7063188/c9015988-62dd-4d8d-bd82-116adca91c0d)
![image](https://github.com/gofiber/fiber/assets/7063188/19b1f51c-9c8b-452a-ab76-f7936d60efdd)

the objection is correct, just don't know if we should change the signature

That would be another breaking change
the question is how best the usage is for the comsumer in such a case

breaking change would still work if necessary, but then I want to be sure that we don't make the whole thing complicated, because currently it is a simple function for simple access
but this access becomes more complicated for all other values which were simple before
although the case that it is a list probably only occurs in 0-3% of the cases

i.e. we have to be clear whether we want to adjust all other simple cases with the signature change and thus adjust the ease of access based on these 3% cases and thus cause a breaking change or whether the simple solution with the comma separated values would also work

currently not sure, the signature change seems to be more correct, but also makes it more complicated

**Comment by ReneWerner87** [comment]
@gaby @efectn let's talk together again about the possible solution

**Comment by Skyenought** [comment]
@ReneWerner87 

I think it's a good idea to use a comma separator, so that when the user fetches the value and finds a separator in the middle, they'll find the Header that needs special handling.

 A solution to change the signature of a function can be used in v3.

**Comment by ReneWerner87** [comment]
> @gaby @efectn let's talk together about the possible solution
> 

We have made an internal vote in the maintainer cycle and decided for the variant with the string list, so the signature change

So we accept this change as pr

**Comment by trco** [comment]
Should the initial [bug](https://github.com/gofiber/fiber/issues/2594#issue-1862825964) be fixed with this? When I'm making request with 'Content-Type: test1' and 'Content-Type: test2' I'm getting only "Content-Type": ["test2"] in the map returned by GetReqHeaders method. Using latest version 2.51.0.

**Comment by ReneWerner87** [comment]
is due to this header, this is a valid example
does it make sense to assign several values to the content type in the request?
with all other headers it works by the way

![image](https://github.com/gofiber/fiber/assets/7063188/e7d935e1-167a-4a5d-8055-4a973555dcbf)

![image](https://github.com/gofiber/fiber/assets/7063188/d6abcca1-0ca0-4a8d-a3f6-8c8ba2874445)

**Comment by trco** [comment]
Wow. My bad. While testing I simply duplicated the first header and didn't pay attention to the context of the header itself. Thanks for your reponse.

**Comment by trco** [comment]
> Wow. My bad. While testing I simply duplicated the first header and I didn't pay attention to the context of the header itself. Thanks for your reponse.
