### ISSUE TITLE
HTTP/2 support 🤔 

### ISSUE THREAD

**Issue by shiftrtech** [gofiber/fiber#262]
Does fiber support http 2 or are there any plans to.

Thanks.

**Comment by renanbastos93** [comment]
> Does fiber support http 2 or are there any plans to.
> 
> Thanks.

Hello, we use the lib FastHTTP as our HTTP server, and it doesn't implement yet supported to http2. 

TODO:
[- HTTP/2.0. See https://tools.ietf.org/html/rfc7540 .](https://github.com/valyala/fasthttp/blob/a1cfe58ca86648c6701f1cb7e8b1587348dd5b9f/TODO#L4)

But it being implemented support the HTTP2 in this link
https://github.com/fasthttp/http2

Well, coming soon we have support in Fiber.

**Comment by Fenny** [comment]
@shiftrtech thanks for opening your first issue, welcome!

Like @renanbastos93 mentioned, we run on the [Fasthttp)(https://github.com/valyala/fasthttp) engine and currently has no support for `HTTP/2.0`.

Keep in mind that `HTTP/2.0` is often taken care off by any load balancer / proxy like [NGINX](https://www.nginx.com/), [Cloudflare](https://www.cloudflare.com/), [Akamai](https://www.akamai.com/) etc and they do not support `HTTP/2.0` communication to the backend server.

Reference https://stackoverflow.com/questions/41637076/http2-with-node-js-behind-nginx-proxy
_There is almost no sense to implement it, as the main HTTP/2 benefit is that it allows multiplexing many requests within a single connection, thus [almost] removing the limit on number of simalteneous requests - and there is no such limit when talking to your own backends. Moreover, things may even become worse when using HTTP/2 to backends, due to single TCP connection being used instead of multiple ones._

But as soon Fasthttp will support HTTP/2, we will too 👍 
I hope I answered your question.

**Comment by renanbastos93** [comment]
At my work, we give support to http/2.0 too. We have a CDN and working with Edge Computing. www.azion.com
@aziontech

**Comment by Fenny** [comment]
@shiftrtech I hope this answers your question, feel free to re-open :+1:

**Comment by dgrr** [comment]
Hello. I just saw this issue by mistakenly typing http2 gofiber.io on my searchbar hehe.

So, there's a server to test http2 for fasthttp (and gofiber too) [here](http2.gofiber.io). I am building the http2 support [here](https://github.com/dgrr/http2). The library is more focused on clients than servers, but it works for servers too. As far as I see it works quite well, but I'd like to do more testing.
