### ISSUE TITLE
🤗 [Question]:    should CSRF Token generated by CSRF middleware be a fixed value?

### ISSUE THREAD

**Issue by rere61** [gofiber/fiber#2627]
### Question Description

The CSRF Token generated by CSRF middleware  is a  fixed token value(ex: 2a8893b9-5a98-4be6-ac1f-c4840c52f6bd ) in for every post request, fixed token value could be vulnerable although it will expire at some time.

> CSRF token is simply duplicated in a cookie
> In a further variation on the preceding vulnerability, some applications do not maintain any server-side record of tokens that have been issued, but instead duplicate each token within a cookie and a request parameter. When the subsequent request is validated, the application simply verifies that the token submitted in the request parameter matches the value submitted in the cookie. This is sometimes called the "double submit" defense against CSRF, and is advocated because it is simple to implement and avoids the need for any server-side state:
> 

reference:
https://portswigger.net/web-security/csrf/bypassing-token-validation
https://owasp.org/www-community/attacks/csrf

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

csrfMiddleware = csrf.New(csrf.Config{
		KeyLookup:      "form:X-Csrf-Token",
		CookieName:     "X-Csrf-Token",
		CookieSameSite: "Strict",
		CookieHTTPOnly: true,
		CookieSecure:   true,
		Expiration:     3 * time.Hour,
		Storage: fiberRedisStore.New(fiberRedisStore.Config{
			URL:   config.GConfig.CSRFSessionURL,
			Reset: false,
		}),
		KeyGenerator: func() string { return uuid.New().String() },
	})
app.Use(csrfMiddleware );
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
what is the idea or question?

**Comment by rere61** [comment]
> what is the idea or question?

When I use csrf middleware, it will generate a csrf token for me (ex: 2a8893b9-5a98-4be6-ac1f-c4840c52f6bd), and after the user did a succssful POST request, the csrf token does not change, so the user could use the same token value do POST again,  it seems not a usual case.

**Comment by ReneWerner87** [comment]
what would be your idea for restructuring the code?

**Comment by ReneWerner87** [comment]
you mean it should expire after the matching? so that for the next request a new one must be generated?

**Comment by rere61** [comment]
> you mean it should expire after the matching? so that for the next request a new one must be generated?

Yes. You feel me.

**Comment by gaby** [comment]
I'm confused, the expiration is hard coded here: https://github.com/gofiber/fiber/blob/master/middleware/csrf/csrf.go#L52 but further below it uses the one fron the config https://github.com/gofiber/fiber/blob/master/middleware/csrf/csrf.go#L77

**Comment by gaby** [comment]
Default expiration is 1hr https://github.com/gofiber/fiber/blob/master/middleware/csrf/config.go#L112

**Comment by rere61** [comment]
> Default expiration is 1hr https://github.com/gofiber/fiber/blob/master/middleware/csrf/config.go#L112

A fixed CSRF token can pose security issues, unrelated to its expiration time. After each successful request, a new CSRF token must be generated. Please refer to the following webpage for more information.

CSRF token is simply duplicated in a cookie
In a further variation on the preceding vulnerability, some applications do not maintain any server-side record of tokens that have been issued, but instead duplicate each token within a cookie and a request parameter. When the subsequent request is validated, the application simply verifies that the token submitted in the request parameter matches the value submitted in the cookie. This is sometimes called the "double submit" defense against CSRF, and is advocated because it is simple to implement and avoids the need for any server-side state:

**Comment by the-hotmann** [comment]
@rere61

logically this makes sense, but it creates some problems when not implemeted properly and a client openes multiple tabs/pages at the same time.

When a user has two tabs/pages open, it will not work properly in some cases. So not really all requests need new CSRFs, and if they do, all CSRFs shall be stored in the users session - if one matches a valid CSRF then is shall be considered as having the (one or more) correct CSRFs.
I would go with something like this: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern

> CSRF tokens should be:
> 
> Unique per user session.
> Secret
> Unpredictable

**Comment by sixcolors** [comment]
@rere61 CSRF tokens are primarily used to secure sessions, and making them one-time use could pose issues, especially in scenarios where users have multiple tabs open. 

I would like to suggest an alternative solution to the issue you've raised: considering the use of idempotency tokens. Fiber already provides middleware for idempotency handling, which can be a more suitable approach in cases where you need to prevent duplicate requests or ensure idempotent behavior. You can find this middleware here: [Fiber Idempotency Middleware](https://github.com/gofiber/fiber/tree/master/middleware/idempotency).

I would recommend closing this issue. What do you think?

**Comment by sixcolors** [comment]
## Security Threat Model for Go Fiber's CSRF Middleware with HTTPS

**CSRF Threat**: Cross-Site Request Forgery (CSRF) attacks are a significant security threat to web applications. In a CSRF attack, a malicious website tricks an authenticated user into unknowingly performing actions on a different web application, leading to unauthorized actions being taken on the user's behalf.

**CSRF Protection Objective**: Go Fiber's CSRF middleware is designed to mitigate CSRF threats by ensuring that incoming requests to the protected web application are valid and initiated by users making subsequent requests from the same-site. It aims to prevent unauthorized actions and safeguard the application's integrity.

**Cross-Site Request Context with HTTPS**: When considering CSRF protection in the context of HTTPS, several important aspects come into play:

1. **HTTPS Encryption**: HTTPS encrypts the communication between the client (browser) and the server. This encryption ensures the confidentiality and integrity of data transmitted between them. It safeguards sensitive information, including CSRF tokens, from being intercepted or tampered with by attackers during transit.
2. **Cookies and Same-Site Policy**:
  - By default cookies set with the "SameSite=Lax" attribute are sent with top-level navigation, which includes some cross-site requests. Developers using the CSRF middleware needs to account for this behavior when validating tokens using the CsrfFromCookie extractor.
3. **Headers and Request Bodies**:
  - In cross-site scenarios, when a user initiates a request to the protected web application, the browser includes cookies (including the CSRF token cookie) and headers in the request.
  - The CSRF token, in this case, is typically transmitted in the request headers or as part of the request body. The middleware validates these headers or request bodies to ensure the authenticity of the CSRF token.
4. **Token Separation**:
  - Go Fiber's CSRF middleware handles the CSRF token, and the session middleware validates the session token separately. These tokens are generated and retrieved differently depending on the HTTP method, and they are not aware of each other.
  - In the default configuration: The CSRF token is extracted from headers, while the session token is typically stored as a cookie. This separation minimizes the risk of unintended token exposure.
5. **Token Expiry and Revalidation**:
  - CSRF tokens have a predefined expiration time. After this time, the token is no longer valid, and the middleware ensures that expired tokens are not accepted.
  - Upon each valid request, the middleware may reissue a new CSRF token, effectively rotating the token for enhanced security.
6. **Vary Header for Caching Prevention**: The middleware adds the Vary header with the value fiber.HeaderCookie to prevent caching of responses. This further enhances security by ensuring that CSRF tokens are not cached inadvertently.
10. **Developer Responsibility**: Developers using Go Fiber's CSRF middleware must configure it correctly, taking into account HTTPS, cookie attributes, and security settings.

Proper usage of the CSRF and session tokens is crucial to maintain security in cross-site scenarios.

**Request for Example Exploit**: @rere61 In order to provide more targeted guidance on CSRF threat mitigation and to further assist with addressing your concerns, I kindly request that you share an example CSRF exploit scenario or any specific questions related to CSRF protection that you may have. This would allow us to tailor our responses to your needs more effectively and offer practical insights into protecting your web application from CSRF attacks.
