### ISSUE TITLE
Allow to serve a custom listener🔥 

### ISSUE THREAD

**Issue by encendre** [gofiber/fiber#265]
**Is your feature request related to a problem?**
Hi, I'd like to use fiber on a unix socket.

**Describe the solution you'd like**
The most natural way to do this is to add `(app *App) Serve(ln net.Listener)` function.

**Describe alternatives you've considered**
Also an alternative could be to expose the `app.newServer()` and then use `app.NewServer().Serve(ln)` on the listener.

**Comment by Fenny** [comment]
We could add this for `v1.9.0` 👍 
```go
package main

import (
	"log"
	"net"

	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Hello, World!")
	})

	ln, err := net.Listen("tcp", ":3030")
	if err != nil {
		log.Fatal(err)
	}

	app.Serve(ln)
}

```

**Comment by encendre** [comment]
Both are okay, but I think it's better to have a separate method.

**Comment by mthli** [comment]
`app.Serve(ln net.Listener)` is better, I think it should be the method that allow users custom what they want as much as possible.

But I'm interested in how to combine fiber's listener which created from `app.prefork()` or `net.Listen()`  and user's custom listener, since `tls.NewListener()` only allow nest (or wrap) listener?

**Comment by Fenny** [comment]
@mthli , good point. I think `app.Serve(ln net.Listener)` cannot support the `preforking` feature. If we add this to the docs, it should be no problem.
