### ISSUE TITLE
🤗 [Question]: app.Static(...) function sends content-type "text/plain" instead of "application/javascript"

### ISSUE THREAD

**Issue by yaghoubi-mn** [gofiber/fiber#2659]
### Question Description

hello
i work in project with gofiber and react
when i serve the static files with app.Static("...", "...") the browser send request for main.jsx file and server send response, the problem is server should send content-type "application/javascript" and instead of it, server send "text/plain", and browser block the file after file received.
how can i fix it.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by peczenyj** [comment]
I think the issue came from fasthttp


https://github.com/valyala/fasthttp/blob/master/fs.go#L1324
```go
func (h *fsHandler) newFSFile(f *os.File, fileInfo os.FileInfo, compressed bool, fileEncoding string) (*fsFile, error) {
...
	// detect content-type
	ext := fileExtension(fileInfo.Name(), compressed, h.compressedFileSuffixes[fileEncoding])
	contentType := mime.TypeByExtension(ext)
	if len(contentType) == 0 {
		data, err := readFileHeader(f, compressed, fileEncoding)
		if err != nil {
			return nil, fmt.Errorf("cannot read header of the file %q: %w", f.Name(), err)
		}
		contentType = http.DetectContentType(data) // this probably is reading data and setting the wrong content type
```

you can test local if your system can recognize the extension .jsx

```go
package main

import (
	"fmt"
	"mime"
)

func main() {
	fmt.Println("jsx", mime.TypeByExtension(".jsx"))
	fmt.Println("js", mime.TypeByExtension(".js"))
}
```

if not, you have two options:

  1. add/update the .jsx into one of the mime type files https://pkg.go.dev/mime#TypeByExtension
  2. you can add a handler to modify the response and update the content type on such cases: https://pkg.go.dev/github.com/gofiber/fiber/v2#Static like this example: https://github.com/gofiber/fiber/blob/master/app_test.go#L929
  
enjoy

**Comment by ReneWerner87** [comment]
this problem has been documented many times and is due to the golang version and or operation system 

https://github.com/gofiber/fiber/issues/352
https://github.com/gofiber/fiber/issues/1763
https://github.com/golang/go/issues/32350


check this
https://github.com/golang/go/issues/32350#issuecomment-635859542

**Comment by yaghoubi-mn** [comment]
Thanks for your helps
i searched more and i found the solution
the solution: i must build the react app (npm run build) and the set static to builded file (app.Static("/", "frontend/dist"))

@peczenyj your solution work but the browser can't read jsx file and it got syntax error

@ReneWerner87 i'm not have windows but i searched to add jsx type to linux mime database but i can't do it.

Thanks

**Comment by ReneWerner87** [comment]
since you have found the solution, i will close the issue
