### ISSUE TITLE
🧹 [Maintenance]: Update RFC Draft for Idempotency Middleware

### ISSUE THREAD

**Issue by gaby** [gofiber/fiber#2913]
### Maintenance Task Description

The draft RFC for the idempotency middleware links to a draft documentation that expired 1 year ago. We should compare the one linked in the documentation with the latest draft and update the middleware accordingly.

Draft in Docs: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-idempotency-key-header-02
Latest Draft: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-idempotency-key-header-04

### Checklist:

- [X] I have confirmed that this maintenance task is currently not being addressed.
- [X] I understand that this task will be evaluated by the maintainers and prioritized accordingly.
- [X] I am available to provide further information if needed.

**Comment by gaby** [comment]
Note: I noticed this while updating/cleaning the README.md in a local branch.

**Comment by ledex** [comment]
The latest draft currently is https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-idempotency-key-header-05.
The only differneces I see between draft-02 and draft-05 are:
- The addition of the following paragraph in 2.5:

  > Clients MAY choose to send an Idempotency-Key field with any valid
   random sf-string to indicate the user's intent is to only perform
   this action once.  Without a priori knowledge, a general client
   cannot assume the server will respect this request.
- The usage of SHOULD in 2.6:
  > The request was retried before the original request completed.
      The resource server ~~MUST~~ **SHOULD** respond with a resource conflict error.
      See Error Scenarios for details.
- HTTP status code 422 is now called "Unprocessable ~~Entity~~ **Content**"
(Which is due to the "newly" proposed [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110#name-422-unprocessable-content).)

The other changes are non-technical. Therfore I don't see the need for updating the middleware.

Diff can be found [here](https://author-tools.ietf.org/iddiff?url1=draft-ietf-httpapi-idempotency-key-header-02&url2=draft-ietf-httpapi-idempotency-key-header-05&difftype=--hwdiff).

**Comment by gaby** [comment]
@ledex Thanks for the analysis
