### ISSUE TITLE
🤗 [Question]: Is the Ctx.BodyParser missing in v3?

### ISSUE THREAD

**Issue by rolandihms** [gofiber/fiber#2958]
### Question Description

Hi Guys,

New to Go/Fiber and really been enjoying it. I have noticed that the BodyParser is missing in the v3 branch. The v3-alpha still includes it and the documentation is still referring to the method.

#https://github.com/gofiber/fiber/blob/v3-alpha/ctx.go#L336

Latest:

#https://github.com/gofiber/fiber/blob/main/ctx.go

Is this correct, are the docs simply outdated? 

#https://docs.gofiber.io/api/ctx#bodyparser

Appreciate any feedback,

Thanks

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()
  type payload struct {
	Html string `json:"html"`
  }
  app.Post("/html", func(c fiber.Ctx) error {
	body := new(payload)
	if err := c.BodyParser(body); err != nil {
	    return err
	}
	log.Println("html", body.Html)
	return c.Send(c.Body())
  })
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by grivera64** [comment]
Hi @rolandihms,  yes I believe the docs are still being updated for v3. `c.BodyParser()` was removed in v3 in favor of moving implementation details for binding payloads to a struct and related tasks into a new `*fiber.Bind` struct located at [fiber/bind.go](https://github.com/gofiber/fiber/blob/main/bind.go#L22). You can get a pointer to this struct by using the `c.Bind()` defined in [fiber/ctx_interface.go](https://github.com/gofiber/fiber/blob/main/ctx_interface.go#L373).

To upgrade your code snippet to use the new `c.Bind()` method, it would look like this:

```go
package main

import (
    "github.com/gofiber/fiber/v3"
    "log"
)

type payload struct {
    Html string `json:"html"`
}

func main() {
    app := fiber.New()
    app.Post("/html", func(c fiber.Ctx) error {
        body := new(payload)
        if err := c.Bind().JSON(body); err != nil {
	    return err
	}
	log.Println("html", body.Html)
	return c.Send(c.Body())
    })
    log.Fatal(app.Listen(":3000"))
}
```

Also, did you mean to use `return c.Send(body)` instead of `return c.Send(c.Body())`? Sending `c.Body()` wouldn't require using `c.Bind().JSON()` within the `POST /html` handler in this example.

I hope this is helpful!

**Comment by rolandihms** [comment]
Thanks @grivera64 makes perfect sense thank you.
