### ISSUE TITLE
change from os.Args scan to flags

### ISSUE THREAD

**Issue by CommoDor64** [gofiber/fiber#301]
## Current state
Command line flags are being scanned explicitly, this reduces readability, can introduce bugs and make future changes more difficult

## Proposal
Delegating this responsibility to [https://golang.org/pkg/flag/](url), as it is 1st party, idiomatic and very easy to use with little chances to introduce any issues.

It will also allow to delegate all flag parsing to a dedicate file or package
## Example
*app.go*
```go
func isPrefork() bool {
	for _, v := range os.Args[1:] {
		if v == "-prefork" {
			return true
		}
	}
	return false
}
```

turns to
```go
var isPrefork bool
func init() {
	flag.boolVar(&isPrefork, "prefork", 1234, "enable multiple goroutines to listen to a socket")
}
```

**Comment by CommoDor64** [comment]
Not a bug, but not a feature either.

**Comment by thomasvvugt** [comment]
Hi @CommoDor64 , thanks for creating this issue!
I also prefer using Go's default flag package to parse any program arguments.
However, I doubt if @Fenny had any design choices for using `os.Args` back when he created the application.
If you like, you can submit a pull request for this change.

If you have any questions, please let me know!

**Comment by CommoDor64** [comment]
Sounds great.
I will work on it, is it possible to assign it to me?

**Comment by thomasvvugt** [comment]
Great, I assigned you to this issue as well.
Thanks for your commitment so far!

**Comment by Fenny** [comment]
@CommoDor64 thanks for your commitment! The reason we switched to reading the `os.Args` was because of https://github.com/gofiber/fiber/issues/159 it created conflicts with other libraries who use the same arguments. `flag.Parse` also crashed our benchmarks running on docker at https://github.com/TechEmpower/FrameworkBenchmarks. Fasthttp had the same issues when used with different libraries and they also switched to `os.Args` https://github.com/valyala/fasthttp/blob/master/prefork/prefork.go#L76

**Comment by CommoDor64** [comment]
I suspected there was a valid reason for it.
But since there are only two flags so far, I think we can close it for now if you want (:

**Comment by Fenny** [comment]
@CommoDor64 thanks for your feedback, I do agree that using the default functions is the best practice. We might come back to this in the future 👍
