### ISSUE TITLE
🐞 Multiple Bugs

### ISSUE THREAD

**Issue by rebootcode** [gofiber/fiber#327]
### **Fiber version/commit**
1.9.3

### **Issue description**

**Bug 1:**

- ./main.go:8:33: cannot use fiber.Settings literal (type fiber.Settings) as type *fiber.Settings in argument to fiber.New

Code was taken from here - https://docs.gofiber.io/application#settings

```
app := fiber.New(fiber.Settings{
	Prefork: true,
	CaseSensitive: true,
})
```

===================

**Bug 2: Directory Index is Forbidden**
**Bug 3: "bind variable is empty in template -- {{ .bind.Title }} "**

My Architecture

- app/main.go
- templates/index.html
- public/assets/{img|css|js}

Code:

```
app.Use("/", func(c *fiber.Ctx) {
		c.Set("X-Server-Header", "localhost")
		c.Append("MyHost", "http://localhost")
		c.Next()
	})

	app.Static("/", "./public", fiber.Static {
		Compress: true,
	})

	app.Get("/", func(c *fiber.Ctx) {
		bind := fiber.Map{
			"Title": "Network",
			"Host":  c.BaseURL()+"/",
		}
		if err := c.Render("./templates/home.html", bind); err != nil {
			c.Status(500).Send(err.Error())
		}
	})
```
Again take from example page https://docs.gofiber.io/application

### go version
go version go1.14.2 linux/amd64

**Comment by rebootcode** [comment]
But, the Directory index issue is gone, When I use "Static" function at end of the file like below:

```
app.Get("/", func(c *fiber.Ctx) {
		bind := fiber.Map{
			"Title": "Network",
			"Host":  c.BaseURL()+"/",
		}
		if err := c.Render("./templates/index.html", bind); err != nil {
			c.Status(500).Send(err.Error())
		}
	})

	app.Static("/", "./public", fiber.Static {
		Compress: true,
	})
```

**Comment by Fenny** [comment]
Hi @rebootcode, thanks for opening your first issue on fiber.
I fixed the following things:
- The [API Docs](https://docs.gofiber.io/application) had a wrong example, it should have been `fiber.New(&fiber.Settings{})`
- The `Directory Index is Forbidden` error will be fixed in this PR https://github.com/gofiber/fiber/pull/329 (nice catch)
- Regarding the missing variable in the render function, it's default behaviour since the `text/template` package does not throw an error on a missing variable.

I hope this solves your problem, thank you for your contribution and welcome to fiber.

**Comment by rebootcode** [comment]
Great!

- Bug 1 is gone
- Bug 2 not yet tested - Is there going to be any new Patch version released to pull via go.mod?
- Bug 3 - Found out - It maps directly to the template without variable name.

```
bind = fiber.Map { "Title": "This Title", "Host": "HTTP://locahost" }
```

In Template - `{{ .Title }}` is available with the value `{{ .bind.Title }}` is not.

**Comment by Fenny** [comment]
@rebootcode you are correct regarding point 3. Bind should not be in the variable namespace.

Regarding point 2, expect a new release within the next 2-3 days.

**Comment by rebootcode** [comment]
Ok. Great!

Thanks
