### ISSUE TITLE
It is possible to send logger Output to a database 🤔 

### ISSUE THREAD

**Issue by saul-gush** [gofiber/fiber#495]
**Question description**
I have been looking to try intercept the Output of the logger, instead of recording to io.Writer and avoid writing logs to disk, I would like to capture that in a database. 

What is the best way to do that?

**Comment by Fenny** [comment]
This is easily doable, because the [io.Writer](https://golang.org/src/io/io.go?s=3794:3855#L80) interface contains a single `Write` method.

So basically you just need to create a type that implements io.Writer, and whose Write() method inserts the log into your database.

Here's a simple implementation which demonstrates that:
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
)

type DBLogger struct{}

func (dbl *DBLogger) Write(log []byte) (n int, err error) {
	// insert string(log)
	return len(log), nil
}

func main() {
	app := fiber.New()

	app.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		Format: "${method} - ${path}",
		Output: &DBLogger{},
	}))

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Hello 👋!")
	})

	app.Listen(3000)
}
```

**Comment by saul-gush** [comment]
This is perfect, thank you!
