### ISSUE TITLE
🚀 Use middleware for all paths except starting with the prefix

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [gofiber/fiber#505]
I have a situation when i need to use authorization middleware for all paths, except ones that start with `/internal-api` prefix. But currently, `Use` method doesn't implement such functionality.

What i propose is if `Use` is called with prefix and prefix is starting with `^` symbol -- consider that middleware should be applied to all paths except ones that start with prefix. Another option would be to handle prefix as regexp, but that probably would be overkill.

**Comment by Fenny** [comment]
Hi @GrigoriyMikhalkin, thanks for opening your first issue here!

Since we want to replicate expressjs behavior regarding routing, your suggestion will probably not be an ideal solution.
Here are some examples that could solve your issue using order or some small middleware checks.

**Order is a thing**
```go
func main() {
	app := fiber.New()

	app.Get("/internal-api/get", handler)
	app.Put("/internal-api/put", handler)
	app.Post("/internal-api/post", handler)

	app.Use(func(c *fiber.Ctx) {
		// authorization mw
		c.Next()
	})

	app.Get("/secret", handler)
	app.Get("/admin", handler)

	app.Listen(3000)
}
```

**Check the prefix within the middleware**
```go
func main() {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) {
		if !strings.HasPrefix(c.Path(), "/internal-api") {
			c.Next()
		}
	})

	app.Get("/internal-api/get", handler)
	app.Put("/internal-api/put", handler)
	app.Post("/internal-api/post", handler)

	app.Get("/secret", handler)
	app.Get("/admin", handler)

	app.Listen(3000)
}
```

I hope this answered your question. A quick side note, we are working on regex support within routes 👍

**Comment by GrigoriyMikhalkin** [comment]
@Fenny Thanks for answer! I currently use second approach. First approach also looks nice, would be good to document it in docs(at least i didn't saw it anywhere before)

**Comment by Fenny** [comment]
Yeah, it would be a good idea to document that order matters like in expresses. I'm closing this issue, for now, feel free to re-open if you have any further questions 👍
