### ISSUE TITLE
🤔 Query a key that contains multiple values.

### ISSUE THREAD

**Issue by ctanpf** [gofiber/fiber#510]
I'm a Flask user and in Flask we can extract a list of values from a single query key via `versions = args.getlist('version')`

So, when I hit this endpoint `https://domain/api/os?version=1&version=2&version=3`, I can get a list of `versions = [1,2,3]`  

But it looks like I can only extract the first value since the `ctx.Query()` only `peek` the value. Do I need to access the `ctx.Fasthttp.QueryArgs()` to get the map? I'm fairly new to Go so any help will be appreciated.

**Comment by Fenny** [comment]
Hi @ctanpf and welcome, thank you for opening your first issue! 🥳 

[RFC 3986](http://tools.ietf.org/html/rfc3986#section-3.4) has a section `3.4. Query`, which refers to key=value pairs, but nothing is said on how to interpret order and duplicate fields and so on. 

This means you may do what you like but at the same time duplicate keys have no standard when it comes to the order of the values (`first-given`, `last-given`, `array-of-all`,), in addition to the server keeping the order of the query string, there is also the question about the browser sending them in DOM (or some other fixed) order.

This report from [OWASP](https://www.owasp.org/images/b/ba/AppsecEU09_CarettoniDiPaola_v0.8.pdf) that analyzed HTTP Parameter Pollution attacks. `Page 9` clearly shows that many frameworks are inconsistent when it comes to parsing duplicate queries. Some only use the first or last occurrence.

For your use case, you could also use one query key and divide the values with `,` for example, this way you have a consistent result on both the server and client-side. `/os?version=1,2,3`.

Since it's use-case depended and we want to keep Fiber's API as clean as possible and in line with [expressjs](https://expressjs.com/en/4x/api.html#req). I think that this would not have a valid purpose in this framework.

If you are stuck with `/os?version=1&version=2&version=3` my advice would be to use the `ctx.Fasthttp.QueryArgs().PeekMulti("version")` or create a custom function within your application using this endpoint.

I hope this answered your question, if you don't have further questions feel free to close this issue 👍

**Comment by ctanpf** [comment]
Thank you so much. I actually figured it out. This is my sample code. 
```
func GetArgs(c *fiber.Ctx) map[string][]string {
	argsMaps := make(map[string][]string)
	queryKeys := []string{"os", "version"}
	for _, keys := range queryKeys {
		param := c.Fasthttp.QueryArgs().PeekMulti(keys)
		for _, value := range param {
			argsMaps[keys] = append(argsMaps[keys], string(value))
		}
	}
	return argsMaps
}
```

If you hit `http://test/api/os?os=BigSur&os=Mojave&version=11&version=12`

GetArgs will returns a map of 
```
{ 
    "version" => ["11", "12]
    "os" =>  ["BigSur", "Mojave"]
}
```

**Comment by monstermichl** [comment]
In case some is trying to get this working in newer versions:
```golang
ctx.Request().URI().QueryArgs().PeekMulti()
```
