### ISSUE TITLE
🐛 Headers in ErrorHandler 

### ISSUE THREAD

**Issue by sxwebdev** [gofiber/fiber#562]
**Fiber version**
12.4

How to use Headers from middlewares in custom ErrorHandler ?

![image](https://user-images.githubusercontent.com/3129246/86820938-69bd6700-c092-11ea-8a45-c0124a2ca1b8.png)

When I get error, my headers looks like this

![image](https://user-images.githubusercontent.com/3129246/86821239-d2a4df00-c092-11ea-83f6-293b06145de2.png)

Headers should look like this

![image](https://user-images.githubusercontent.com/3129246/86821342-f405cb00-c092-11ea-8876-e15081fa7fc2.png)

**Comment by Fenny** [comment]
Hi @sxwebdev, it's a design choice to [reset the response headers](https://github.com/gofiber/fiber/blob/master/ctx.go#L607) when the `ErrorHandler` is called. The reason we did this is because when an error occurs, the original response is not valid anymore. Especially when you are working with sensitive headers, this could be a security risk.

I hope this answered your question, feel free to close this issue or provide additional comments 👍

**Comment by sxwebdev** [comment]
Hey @Fenny. Thank you for responding quickly. If I understand correctly, then in the error handler I need to add all the necessary headers separately? as written below

```
ctx.Set(key,value)
ctx.Set(key,value)
ctx.Set(key,value)
```

**Comment by Fenny** [comment]
Hey @sxwebdev, that is correct. Depending on how you want to handle the error, you could add any response headers like you mentioned in your example 👍

**Comment by sxwebdev** [comment]
Thanks!

**Comment by Fenny** [comment]
@sxwebdev, your issue started a discussion in our [Discord](https://gofiber.io/discord) channel. And after some discussion, we changed our mind regarding the header reset behavior and are planning to remove it for `v1.12.16` 👍

**Comment by Fenny** [comment]
@sxwebdev Tagged in [v1.12.6](https://github.com/gofiber/fiber/releases/tag/v1.12.6) 👍
