### ISSUE TITLE
Function naming issues under `fiber.Ctx`

### ISSUE THREAD

**Issue by iredmail** [gofiber/fiber#766]
Confused function names and suggested to rename them:

- `c.Params(...)` is now used to get parameters in URL path, but it looks like returning all parameter names in a form. Maybe `c.URLParam` is clearer? https://docs.gofiber.io/api/ctx#params
- `c.Get(...)` is not clear, it looks like getting value of form parameter. Maybe rename it to `c.Header(...)`, or `c.GetHeader(...)`. https://docs.gofiber.io/api/ctx#get
- `c.OriginalURL(...)` is confusing too. it looks like getting original url after http 301/302 redirection. but it "returns the original request URL." Better rename to something like `c.URLQueryString(...)` or `c.QueryString(...)`.
- `c.FormValue(...)` is clear but long, maybe use `c.Get(...)` directly.

Request new functions:

- Function used to get all form parameter names. e.g. `c.Params(...)` is best option IMO.

**Comment by Fenny** [comment]
Hey @iredmail, thank you for your suggestions!

We follow one of the most popular web framework API drafts ( [expressjs](https://expressjs.com/en/4x/api.html) ), the initial purpose was to help people move to Golang using Fiber as a stepping stone because the API looks familiar.

Even though I agree that some method names are not perfect, they are very familiar to people coming from express. Having said the above, we do not plan to have such breaking changes to our API any time soon.

Everything is well documented in our examples, [API documentation](https://docs.gofiber.io/) and source code.

In case you refuse to use our API layer, you are always free to use Fasthttp [Request](https://docs.gofiber.io/ctx#request) and [Response](https://docs.gofiber.io/ctx#response).

```go
app.Get("/", func(c *fiber.Ctx) error {
    c.Request().Header.Method() // => []byte("GET")
    c.Request().Header.Peek("Accept") // => []byte("text/html")
    c.Response().Write([]byte("Hello, World!"))
})
```
