### ISSUE TITLE
🤗 fiber & fast http configuration questions

### ISSUE THREAD

**Issue by DevDevious** [gofiber/fiber#866]
Hello,

I have noticed that **fiber**'s configuration exposes some of **fasthhttp**'s configuration options "raw" (e.g `ReadTimeout`, `WriteTimeout`, `Concurrency `etc), renames some (e.g **fasthttp**'s `MaxRequestBodySize` becomes `BodyLimit` in **fiber**) and completely ignores others (e.g **fasthttp**'s `MaxConnsPerIP` and `MaxRequestsPerConn`).

Would you consider aligning **fiber**'s config option names with **fasthttp**'s and exposing the missing **fasthhttp** config options through **fiber**'s config?

**Comment by Fenny** [comment]
The reason we left out `MaxConnsPerIP` and `MaxRequestsPerConn` is because we cannot [catch](https://github.com/valyala/fasthttp/blob/master/server.go#L1831) nor forward the error to Fiber and therefore no room for customization to comply with our framework standards. The `MaxConnsPerIP` also uses the tcp IP where this would be a problem if you are behind a load balancer / proxy, you can our [limiter](https://github.com/gofiber/fiber/tree/master/middleware/limiter) middleware to limit requests per IP with the option to set the `ProxyHeader` to get the correct IP. 

We could rename `BodyLimit` to `MaxRequestBodySize`, but I think the shorter versions is well adapted by now, let me know what you think.

**Comment by DevDevious** [comment]
@Fenny

> 
> PS: You could always call:
> 
> ```go
> func (app *App) Server() *fasthttp.Server
> ```
> 

Of course, but instead of setting some configuration fields on **fiber** and others on **fasthttp** wouldn't it be simpler to have one source of configuration for both?

Here is what I collected so far. Is there any strong reason not to normalize the naming and aggregate all of these under fiber's config (+ appropriate documentation notes on caveats related to some settings)?

**Configuration fields unique to fiber** (1)


fiber | fasthttp
-- | --
Prefork | N/A
StrictRouting | N/A
CaseSensitive | N/A
Immutable | N/A
UnescapePath | N/A
ETag | N/A
CompressedFileSuffix | N/A
ProxyHeader | N/A
DisableStartupMessage | N/A




**Configuration fields common to both fiber and fasthttp - same spelling** (2)


fiber | fasthttp
-- | --
Concurrency | Concurrency
DisableKeepalive | DisableKeepalive
ReadBufferSize | ReadBufferSize
WriteBufferSize | WriteBufferSize
ReadTimeout | ReadTimeout
WriteTimeout | WriteTimeout
IdleTimeout | IdleTimeout



**Configuration fields common to both fiber and fasthttp - different spelling** (3)

fiber | fasthttp
-- | --
ServerHeader | Name
BodyLimit | MaxRequestBodySize
GETOnly | GetOnly
DisableHeaderNormalizing | DisableHeaderNamesNormalizing
DisableDefaultDate | NoDefaultDate
DisableDefaultContentType | NoDefaultContentType



**Configuration fields present in **fasthttp** but missing from fiber** (4)


fiber | fasthttp
-- | --
N/A | MaxConnsPerIP
N/A | MaxRequestsPerConn
N/A | TCPKeepalive
N/A | TCPKeepalivePeriod
N/A | ReduceMemoryUsage
N/A | DisablePreParseMultipartForm
N/A | LogAllErrors
N/A | SleepWhenConcurrencyLimitsExceeded
N/A | NoDefaultServerHeader
N/A | KeepHijackedConns

**Comment by Fenny** [comment]
I will accept a PR to add `ReduceMemoryUsage` from `fasthttp`, regarding the other settings I find no good reason to add it to the framework at this point in time.
